### ISSUE TITLE
Linux static build problems with pmem, 14.04 LTS

### ISSUE THREAD

**Issue by adricnet** [google/rekall#100]
Hello,

Using rekall source freshly cloned from git on Ubuntu 14.04 I am able to build pmem normally after installing all of required the libraries and reloading the library cache (sudo ldconfig). Yay!

I'd really like to have static linux binaries as well, but that build gets an error in some of the libraries
when I *./configure --enable-static-binaries*. It seems to unravel in raptor, but I'm not sure where the root of the trouble is. The first few lines output from make are:
```
make  all-am
make[1]: Entering directory `/home/wdcforensics/rekall/tools/pmem'
g++ -DHAVE_CONFIG_H -I.  -I. -DHAVE_SSTREAM -I./../osx/MacPmem/  -std=c++11 -g -Wall -O0 -g -O2 -MT linpmem-pmem_imager.o -MD -MP -MF .deps/linpmem-pmem_imager.Tpo -c -o linpmem-pmem_imager.o `test -f 'pmem_imager.cc' || echo './'`pmem_imager.cc
mv -f .deps/linpmem-pmem_imager.Tpo .deps/linpmem-pmem_imager.Po
g++ -DHAVE_CONFIG_H -I.  -I. -DHAVE_SSTREAM -I./../osx/MacPmem/  -std=c++11 -g -Wall -O0 -g -O2 -MT linpmem-linux_pmem.o -MD -MP -MF .deps/linpmem-linux_pmem.Tpo -c -o linpmem-linux_pmem.o `test -f 'linux_pmem.cc' || echo './'`linux_pmem.cc
mv -f .deps/linpmem-linux_pmem.Tpo .deps/linpmem-linux_pmem.Po
/bin/bash ./libtool  --tag=CXX   --mode=link g++ -std=c++11 -g -Wall -O0 -g -O2 -all-static  -o linpmem linpmem-pmem_imager.o linpmem-linux_pmem.o -laff4 -lglog -lglog 
libtool: link: g++ -std=c++11 -g -Wall -O0 -g -O2 -static -o linpmem linpmem-pmem_imager.o linpmem-linux_pmem.o  -laff4 -lglog
//usr/local/lib/libaff4.a(data_store.o): In function `RaptorParser::NewRaptorParser(DataStore*)':
/home/wdcforensics/aff4/src/data_store.cc:263: undefined reference to `raptor_new_world_internal'
```

I've pasted the whole of the output into a gist:
https://gist.github.com/adricnet/d865082f4ef0407d8636

Rekall source is from git, aff4 is freshly installed from git source, and all else is installed from Ubuntu 14.04 repos including snappy, raptor, uuid, glog, tclap.

Thanks,
adric

**Comment by scudette** [comment]
If you want to build static binaries you must have all dependcies built
statically as well. Normally versions of the libraries distributed with
distributions are not built statically so you need to rebuild everything
from scratch.

There is more info here
http://www.aff4.org/docs/Developers/building.html
Am 16.10.2015 03:36 schrieb "Adric Net" <notifications@github.com>:

**Comment by adricnet** [comment]
Thanks, of course I do :) The scripts at the aff4 site were very helpful .

Cheers,
Ben
