### ISSUE TITLE
live plugin returns unsupported architecture for x86

### ISSUE THREAD

**Issue by dsweet04** [google/rekall#109]
I've tested against both 2003 and 2008 32bit server images on EC2 after installing the Rekall_1.4.1_Etzel_x86 binary. running command prompt as administrator I get back "rekall.plugin.PluginError: Unsupported architecture" for both.

C:\Program Files\Rekall>rekal.exe -v --live pslist
DEBUG:rekall.1:Unable to open \\.\pmem: (2, 'CreateFile', 'The system cannot find the file specified.')
Traceback (most recent call last):
 File "<string>", line 7, in <module>
 File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.rekal", line 104, i
n main
 File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.args", line 397, in
parse_args
 File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.rekal", line 99, in
global_arg_cb
 File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.tools.live_
windows", line 161, in live
 File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.tools.live_
windows", line 96, in load_driver
rekall.plugin.PluginError: Unsupported architecture

**Comment by scudette** [comment]
Thanks for the bug report. I will send a patch shortly. In the meantime you can manually override the choice of driver:

```
rekal.exe -v live --driver "C:\Program Files\Rekal\Winpmem\winpmem_x86.sys"
```

**Comment by scudette** [comment]
Just for the record I looked more into this problem. The offending code is this which tries to detect the architecture of the machine:

https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/tools/live_windows.py#L91

```
        if self.driver is None:
            machine = platform.machine()
            if machine == "AMD64":
                driver = "winpmem_x64.sys"
            elif machine == "I386":
                driver = "winpmem_x86.sys"
            else:
                raise plugin.PluginError("Unsupported architecture")
```

On a 64 bit system platform.machine() returns "AMD64" as it should. I could not find anywhere documented what the values for platform.machine() can possibly be - On a linux system it returns:

```
In [2]: platform.machine()
Out[2]: 'x86_64'
```
When you check the source code for the platform module:
```
     # Try win32_ver() on win32 platforms
        if system == 'win32':
            release,version,csd,ptype = win32_ver()
            if release and version:
                use_syscmd_ver = 0
            # Try to use the PROCESSOR_* environment variables
            # available on Win XP and later; see
            # http://support.microsoft.com/kb/888731 and
            # http://www.geocities.com/rick_lively/MANUALS/ENV/MSWIN/PROCESSI.HTM
            if not machine:
                # WOW64 processes mask the native architecture
                if "PROCESSOR_ARCHITEW6432" in os.environ:
                    machine = os.environ.get("PROCESSOR_ARCHITEW6432", '')
                else:
                    machine = os.environ.get('PROCESSOR_ARCHITECTURE', '')
            if not processor:
                processor = os.environ.get('PROCESSOR_IDENTIFIER', machine)
```

What possible values can this environment variable take:
http://superuser.com/questions/305901/possible-values-of-processor-architecture

- AMD64
- IA64
- x86

So this is an extremely confusing and undocumented API - We need to check for x86 not I386.

**Comment by scudette** [comment]
Obviously a workaround is to just force the environment variable:

```
set PROCESSOR_ARCHITEW6432="I386"
rekal -v --live pslist
```

**Comment by dsweet04** [comment]
Sorry for taking so long to reply to this. I can not edit the environment variable since that may effect other tools. Since --driver is only available as an argument for the "live" module, I don't have a way of specifying the correct driver to run live on 32bit systems from the command line such as:

`rekal --live --driver "C:\Program Files\Rekall\Winpmem\winpmem_x86.sys" pslist`

I'm automating this across many systems from the command line. So I don't have the option of dropping into the interactive shell. If there are any other ways I could get around this as a temporary fix please let me know. Otherwise I guess I will just have to wait for the next release for a 32bit fix.

Thanks again!

**Comment by scudette** [comment]
On windows you can set the evironment variable for just one command (see http://superuser.com/questions/223104/setting-environment-variable-for-just-one-command-in-windows-cmd-exe):

```
cmd.exe /c "set PROCESSOR_ARCHITEW6432=I386 && "c:\Program Files\Rekall\rekal.exe --live pslist"
```

You can also build a windows binary from the latest github head as described here (This bug is fixed in master branch): http://rekall-forensic.blogspot.ch/2015/09/installing-rekall-on-windows.html

**Comment by scudette** [comment]
This should be fixed in the current release.
