### ISSUE TITLE
Store large numbers in string format in Linux profiles

### ISSUE THREAD

**Issue by tklengyel** [google/rekall#112]
Hi all,
I've been trying to get JSON C parsers to be able to process the Linux Rekall profiles to allow LibVMI to use it directly. However, both Jansson and JSON-C fail to properly handle the large 64-bit addresses stored in the profile. Jansson won't even process the file and just fail as it can only process numbers up to 10 digits long, while JSON-C can only handle signed 64-bit numbers, thus returns 9223372036854775807 for nearly all $CONSTANTS.

A workaround for this would be if instead of storing these as numbers to store them as strings so that we can properly convert them to 64-bit unsigned integers in C manually.

Any thoughts?

**Comment by parkisan** [comment]
Maybe you can submit a patch to these libraries so they can parse large
numbers :)

**Comment by scudette** [comment]
Technically the constants are pointers and so have only 48bit precision - maybe we should store them as 48 bits in the profile? Whenever we use them they get sign extended anyway.

**Comment by scudette** [comment]
Its not so easy - those C implementations rely on the underlying sscanf implementation and that might not be supported.  The correct thing is to use strtoull instead of sscanf anyway but this may only be available on gnu systems.  

It should be easy to fix for your architecture but might break on some weird compilers/libcs.

**Comment by tklengyel** [comment]
@parkisan: I would also prefer if those libs would properly handle large numbers but yea, it's not as easy as it sounds. Seems to be a reoccurring problem with a lot of JSON parsers, in JavaScript too. Reading into this another common approach has been to split these numbers into two 32-bit elements which would then get recombined. It's probably a bit faster then parsing a string.

**Comment by tklengyel** [comment]
@scudette: going with 48-bit width would probably solve this issue with JSON-C at least.

**Comment by parkisan** [comment]
Tamas, can you quickly manually convert them to 48-bit and test? I'm right
now redoing the entire Linux repo, so if it works for you I can just do
that everywhere.

**Comment by scudette** [comment]
We are currently redesigning our profile repository so I dont mind rebuilding all the profiles with a new constant format.

Lets just store all the addresses as canonical addresses:
https://en.wikipedia.org/wiki/X86-64#Canonical_form_addresses

You will need to sign extend them when you read them but that should not be a problem. This should also be completely backwards compatible with older Rekall since the pointers are already truncated to 48bits when we call get_constant_object().

**Comment by parkisan** [comment]
I meant you try with a single profile.

**Comment by tklengyel** [comment]
Truncating the address to 48-bit works fine with JSON-C at least:
               `sys_map[symbol] = long(address, 16) & 0xFFFFFFFFFFFF`

**Comment by tklengyel** [comment]
On a related note, have you guys noticed that the pslist output displays only 48-bit truncated VAs as it is (at least with 1.4.1)?

```
0x88007b7d72b0 systemd                   1      0      0      0 0x0000775c1000 2016-01-13 00:41:03+0000
0x88007b7d6960 kthreadd                  2      0      0      0 -              2016-01-13 00:41:03+0000
0x88007b7d6010 ksoftirqd/0               3      2      0      0 -              2016-01-13 00:41:03+0000
0x88007ac609a0 kworker/0:0H              5      2      0      0 -              2016-01-13 00:41:03+0000
```

**Comment by parkisan** [comment]
Yes, whenever we fetch objects from the profile we do it via
Profile.get_constant_object(), which converts it to a canonical address:

https://github.com/google/rekall/blob/master/rekall-core/rekall/obj.py#L2204

This has been this way for a long time.

**Comment by scudette** [comment]
Addresses in Rekall are always 48 bits long everywhere. There is no point cluttering the display with all those sign extended bits. Similarly when the user enters an address it is also truncated to 48 bits (so `dump 0x88007b7d72b0` is the same as `dump 0xffff88007b7d72b0`

**Comment by tklengyel** [comment]
@scudette: OK, I was just checking that it was intentional ;)
