### ISSUE TITLE
plugin request: please port privs plugin

### ISSUE THREAD

**Issue by querist** [google/rekall#114]
Hi! 

Could you please port the Volatility "privs" plugin? It shows which privileges each process has. This is useful for detecting code injection and process modification.

Thanks!
-glyn

**Comment by scudette** [comment]
This is now available in master branch and will go out in the next release.

**Comment by querist** [comment]
Thanks. I've pulled the master and I'm going to try it out. Thanks!

----------------------------
妇女能顶半边天
-- 毛泽东

**Comment by querist** [comment]
I can't seem to make it work on my windows machine even though I have Visual Studio installed. No big deal - I'll pull it onto my Mac tonight and test it there. Thanks again for the quick response!

**Comment by scudette** [comment]
The windows install should be fairly robust:

http://rekall-forensic.blogspot.ch/2015/09/installing-rekall-on-windows.html

**Comment by querist** [comment]
I hate to be difficult...

I read and followed the instructions - I forgot about the VC compiler for
python - everything installed correctly, but when I try to run privs it
tells me that it does not recognise the command. Am I missing something
else?

I'm really sorry about this.

----------------------------
妇女能顶半边天
-- 毛泽东

**Comment by scudette** [comment]
Hi,
  the command is called privileges in Rekall. Do you think we should keep
the same name in Rekall or make it more correct? I personally prefer not to
abbreviate words randomly (and with the command completion you dont need to
type much anyway).

Thanks
Michael.

**Comment by querist** [comment]
Hi Michael,

It still says "unrecognized arguments: privileges" when I try that.

I'll try it on my mac at home tonight. It's reporting version 1.4.1 (Etzel).

Thanks.

----------------------------
妇女能顶半边天
-- 毛泽东

**Comment by querist** [comment]
I can't find it in the master. I don't know what I'm not doing correctly, but the privileges command is no there. I'm running it against a Win 7 memory image, so it should be available.

**Comment by scudette** [comment]
You can see the output of the automated test here:
http://tap.rekall-forensic.com/win7/201602040218/TestPrivileges

This is the command it runs
```
rekall  -v --cache_dir '/home/www-data/rekall-test/win7/../profile_cache/' --format 'test' --filename '/home/www-data/rekall-test/win7/win7.elf.E01' --name_resolution_strategies 'Module' 'Symbol' - privileges
```

This is the image it runs it on:
http://images.rekall-forensic.com/images/win7.elf.E01


Are you sure you are installing from GIT head?

**Comment by querist** [comment]
I will see if I can pull it again. I'm sorry about the confusion.

----------------------------
妇女能顶半边天
-- 毛泽东

**Comment by querist** [comment]
Works perfectly now! I'll to back and make sure I do this properly on my
Mac and my other Windows machine. Thanks again for the help! I'll mark the
issue as closed.

----------------------------
妇女能顶半边天
-- 毛泽东

**Comment by querist** [comment]
Marking issue as closed now that I've learned how to pull properly from GIT and make it work even after having used pip to install rekall the first time.
