### ISSUE TITLE
Not recognizing profiles in repository

### ISSUE THREAD

**Issue by querist** [google/rekall#117]
Hi.

I have the repository from github for offline use. It was working until a few days ago. Now I can run rekall on the aff4 file and it returns the error message in the attached file. I am also attaching my .rekallrc file.  I had to rename it because github would did not allow the real file name.

This is on Windows 8.1. It is working just fine on my Mac.

[pslisterror.txt](https://github.com/google/rekall/files/128498/pslisterror.txt)

[rekallrc.txt](https://github.com/google/rekall/files/128500/rekallrc.txt)

Thanks.

**Comment by querist** [comment]
Curious finding while trying to resolve this issue:
If I remove the profile_path lines in my .recallrc other than the one for my local repository, it works correctly, but naturally would not know where to go look for new profiles.

**Comment by scudette** [comment]
Hi
The parameter is now called repository_path. It was renamed to better
reflect what it was and also due to some limitations in argparse which
confused it with just profile.

You can see what parameters are supported with the --help option. The
.rekallrc file is just the same as the options on the command line.

Thanks
Michael.
Am 12.02.2016 20:47 schrieb "querist" <notifications@github.com>:

**Comment by querist** [comment]
Hi Michael,

It still generates the same error.

I tried changing the order of the paths in the file and it did not help.

**Comment by parkisan** [comment]
From the error it appears that you may be having problems resolving
raw.githubusercontent.com from that machine. Maybe you want to check if you
can do resolution at all from that machine

**Comment by querist** [comment]
Parkisan, the problem is that it should not even be looking for that repository if the profile exists in the local repository. It works when I remove the reference to the external repository, but fails when off-line. If the machine is connected to the Internet, it works correctly.

**Comment by parkisan** [comment]
In that case, it's possible the repository is _not_ being pulled from the
local directory, ever? Because it's not there perhaps?
Have you checked that it's there, both in the nt/GUID directory _and_ in
the inventory.gz?

When was the last time you synced the local profile repo?

**Comment by querist** [comment]
Parkisan, I stated that it works correctly with the local repository if the local repository is the only line in the .rekallrc file, but it fails otherwise.

I pulled the repository down less than a month ago and I tested it against both a memory image from a machine with a recent kernel and against an old (XP) memory image to be sure. Results are the same.

**Comment by scudette** [comment]
A couple of things to try:

1. If you dont want Rekall to use the internet just completely remove (or comment out with # ) the lines which point to the internet.
2. Please always attach output with verbose output (i.e. using -v) flag.
3. To ensure that Rekall is trying to use the right repository please specify the path directly. This will rule out Rekall not being able to find the .rekallrc. Rekall searches for the .rekallrc in the current directory and then in the home directory (and then in /etc/). 

```
$ rekal -v -f ~/images/win7.elf --repository_path c:\lib\rekall-profiles-master\ pslist
```

**Comment by querist** [comment]
Hi Michael,

It works when I specify the path directly and it fails when I don't and I have the .recallrc file that has the path AND the url for the online repository. It works if the .recallrc only has the path to the local repository.

Attaching stderr output from failure (error.txt) and success with manually specifying path (withpath.txt).
[error.txt](https://github.com/google/rekall/files/128764/error.txt)
[withpath.txt](https://github.com/google/rekall/files/128765/withpath.txt)

**Comment by scudette** [comment]
Are you spelling the file .rekallrc?
Am 12.02.2016 22:57 schrieb "querist" <notifications@github.com>:

**Comment by scudette** [comment]
Hi, 
  I looked very carefully at your bug report and there is a bug with the behavior! Thanks for helping us find it. It is very subtle but I think it can be fixed by adding this line in rekall/plugins/tools/caching_url_manager.py:

```
--- a/rekall-core/rekall/plugins/tools/caching_url_manager.py
+++ b/rekall-core/rekall/plugins/tools/caching_url_manager.py
@@ -50,6 +50,8 @@ class CachingManager(io_manager.IOManager):
     order = DELEGATE.order - 10
                                                                                                                                                                                              
     def __init__(self, session=None, **kwargs):
+        self.session = session
+
         cache_dir = os.path.expandvars(session.GetParameter("cache_dir"))
```

Can you please help us test it? I will work on a patch for it.

**Comment by scudette** [comment]
This bug should now be fixed in master branch.

**Comment by querist** [comment]
It works! Thanks!
