### ISSUE TITLE
psscan never finish running

### ISSUE THREAD

**Issue by JohnnieWalker16** [google/rekall#118]
Hi,
I'm running psscan against an 8GB image taken using DumpIt. The plugin never finishes running nor yielding any results. 
It did report scanning the image, tough scanning in non-existing addresses, such as 0x2F000000000. After a while it stops reporting but doesn't stop running, yet consuming no CPU. 

I'm running Rekall on an offline Ubuntu server 14.04 as a module. Other plugins ran against the image did work (though didn't try other scanners), and psscan woeked fine against similar sized images (AFF4 address space) taken from the same machine. 

Ideas?

**Comment by scudette** [comment]
It would be very helpful to include the output with verbose output (-v flag). Are you scanning the virtual address space or the physical address space? Which version of windows is this? Note that dumpit is not a reliable acquisition tool - did you repeat the acquisition with Winpmem 1.6.2?  Do you get the same results with Rekall running in live mode (with --live).

**Comment by JohnnieWalker16** [comment]
Psscan scans the physical address space as far as I know.

The verbose output only shows address space and profile detecting. It runs on an offline system so it's quite complicated to get the whole output. Is there something specific you're looking for? 

The address space is FileAddressSpace and the profile is nt/GUID/3844DBB920174967BE7AA4A2C20440FA2 and the system runs Win7SP1x64. 
Other scanners don't show this kind of behavior. 

The image was taken in July. Later images taken in November using Winpmem 2.0.1 are show no problem, and running Rekall live also goes well.

**Comment by scudette** [comment]
Rekall's psscan usually needs to have a valid kernel address space
reconstructed because it shows you if the process is already known via
pslist. Also in Windows 10 you can't scan for processes in the physical as
anyway.

It's possible that is not able to open the image. Usually we see problems
with dumpit around imaging the kernel so maybe it's not able to detect the
kernel base address. You can verify this by checking the kernel address
space for the mz header around the kernel base.
Am 21.02.2016 2:16 nachm. schrieb "JohnnieWalker16" <
notifications@github.com>:

**Comment by JohnnieWalker16** [comment]
It does detect the kernel base correctly, though the image is clearly faulty. 

However, I think the never-ending plugin is somewhat unwanted behavior, especially for me, as I'm using Rekall as a module running automatically. What can I do to prevent this from happening?

**Comment by scudette** [comment]
We have the same problem in GRR and rekall was specifically designed to
address the issue. You can see that rekall plugins call the
session.report_progress() method very often. You can register a progress
call back on the session and your call back is going to be called all the
time. If you decide to abort (say if the plugin exceeds a certain time or
resource limit) your call back can just raise and the exception will bubble
up the call stack and fail the plugin. This way you can cancel the plugin
at any time. This mechanism is also useful when running a GUI program to
timeslice the GUI rendering if you don't want to use threads.

See rekall-core/rekall/session.py ProgressDispatcher.Register.

It does detect the kernel base correctly, though the image is clearly
faulty.

However, I think the never-ending plugin is somewhat unwanted behavior,
especially for me, as I'm using Rekall as a module running automatically.
What can I do to prevent this from happening?

—
Reply to this email directly or view it on GitHub
<https://github.com/google/rekall/issues/118#issuecomment-186827914>.

**Comment by JohnnieWalker16** [comment]
Works like a charm. Thanks!
