### ISSUE TITLE
Logging problem when using Rekall as a module 

### ISSUE THREAD

**Issue by JohnnieWalker16** [google/rekall#119]
When importing Rekall into python script the logging is always verbose and doesn't consider the level specified using logging.basicConfig, yet does consider the format. 
It also make all other logger log at logging.DEBUG. 
What can I do to make it less verbose?

**Comment by scudette** [comment]
Rekall can use a provided logger to do all logging, you just need to pass it to the session when you make it.

See for example section 5.1 in the tutorial:
http://www.rekall-forensic.com/docs/Manual/tutorial.html

Where we pass the root logger directly to the session. You can create any other logger (and call it whatever you want) and also configure its own logging level just as you want it. See this howto for more information about python logging:
https://docs.python.org/2/howto/logging-cookbook.html#multiple-handlers-and-formatters

This is especially useful if you want to control the verbosity of Rekall compared to other components in the system.

**Comment by JohnnieWalker16** [comment]
The logging verbosity starts with the imports, way before I'm creating a session. 
I passed a logger object I created (with a file handler logging all logs and a stream handler logging errors) but the stream and all other loggers are still verbose.

**Comment by scudette** [comment]
This would mean that one of the imports is setting to the root logger with
basicConfig() for example.

The easiest way to debug it is to add a breakpoint to logging.basicConfig
and see which import is calling it.
Am 24.02.2016 08:37 schrieb "JohnnieWalker16" <notifications@github.com>:

**Comment by parkisan** [comment]
Johnnie, I'd say there's probably at least something wrong on your side
(and maybe a bug on ours).

If you're providing your own stream handler and configuring it properly
(setLevel), I don't see how it can be logging below ERROR. Handlers define
their own logging level and will ignore anything they receive that's below
that
<https://docs.python.org/2/library/logging.html#logging.Handler.setLevel>.


   - If you can show us a snippet of how you're setting up your
   handlers/logger and passing it to the session that may help.
   - Also, are you using Rekall HEAD or 1.4.1? (just for context)

**Comment by JohnnieWalker16** [comment]
I'm not using the HEAD but a clone taken few weeks ago (commit `e594726`) because 1.4.1 raised some errors (which I dont recall)  it solved. 

There's  how I'm defining the logging:

from zlib import error as zlib_error
import os
import time
import sys

import logging
logging.basicConfig(format="%(asctime)s %(levelname)s %(name): %(message)s", level=logging.INFO)

from rekall import plugins # DO NOT remove plugins, it has a job!
from rekall.plugins.renderers import data_export
from rekall import session as rekall_session

_log = logging.getLogger("rekall_session")

if len(_log.handlers) > 1: # Logger already created
	return _log

_log.setLevel(logging.DEBUG)

file_handler = logging.FileHandler(filename="logger.log", mode="a")
file_handler.setLevel(logging.DEBUG)
_log.addHandler(file_handler)

stream_handler = logging.StreamHandler(sys.stdout)
stream_handler.setLevel(logging.INFO)
_log.addHandler(stream_handler)

s = rekall_session.Session(filename=evidence, 
						   autodetect=["nt", "rdsd", "windows_kernrl_file", "linux", "osx"]
						   profile_path="/home/rekalluser/profiles/",
						   logger=_log)

And that's what I'm getting on stdout:
09:10:01,832 INFO   rdflib           : RDFLib Version: 4.2.1
09:10:02,070 INFO   root            : Webconsole disabled: cannot import name webconsole_plugin
09:10:02,271 DEBUG  analyzer         : ###################################################
09:10:02,302 DEBUG  analyzer         : Created 4 processes.
09:10:02,302 DEBUG  analyzer         : Object based on BaseServer was created.
09:14:50,380 DEBUG  rekall_session         : Voting round with base: None
09:14:50,380 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
09:14:50,380 DEBUG  rekall_session         : Failed instantiating VMSSAddressSpace: No base address space provided
09:14:50,380 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
09:14:50,383 DEBUG  rekall_session         : Failed instantiating MACHOCoreDump: Must stack on another address space
09:14:50,383 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
09:14:50,383 DEBUG  rekall_session         : Failed instantiating VMemAddressSpace: No base address space provided
09:14:50,383 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
09:14:50,384 DEBUG  rekall_session         : Failed instantiating EWFAddressSpace: No base address space provided
09:14:50,384 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
09:14:50,384 DEBUG  rekall_session         : Failed instantiating WindowsCrashBMP: Must stack on another address space
09:14:50,385 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
09:14:50,385 DEBUG  rekall_session         : Failed instantiating KCoreAddressSpace: Must stack on another address space
09:14:50,385 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
09:14:50,386 DEBUG  rekall_session         : Failed instantiating WindowsCrashDumpSpace32: No base address space provided
09:14:50,386 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
09:14:50,386 DEBUG  rekall_session         : Failed instantiating WindowsCrashDumpSpace64: No base address space provided
09:14:50,386 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
09:14:50,387 DEBUG  rekall_session         : Failed instantiating Elf64CoreDump: Must stack on another address space
09:14:50,387 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
09:14:50,388 DEBUG  rekall_session         : Failed instantiating LimeAddressSpace: Must be layered on another address space.
09:14:50,388 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
09:14:50,616 INFO   rekall_session         : Added aff4://dffb9bad-4e64-4714-a7c1-8000f205b347/PhysicalMemory as physical memory
09:14:50,631 DEBUG  analyzer         : zlip_physical_withpagefile.aff4 is being analysed in process worker-1.
09:14:50,636 DEBUG  rekall_session         : Succeeded instantiating AFF4AddressSpace
09:14:50,636 DEBUG  rekall_session         : Voting round with base: AFF4AddressSpace
09:14:50,636 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
09:14:50,652 DEBUG  rekall_session         : Voting round with base: None
09:14:50,652 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
09:14:50,652 DEBUG  rekall_session         : Failed instantiating VMSSAddressSpace: No base address space provided
09:14:50,653 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
09:14:50,655 DEBUG  rekall_session         : Failed instantiating MACHOCoreDump: Must stack on another address space
09:14:50,655 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
09:14:50,655 DEBUG  rekall_session         : Failed instantiating VMemAddressSpace: No base address space provided
09:14:50,655 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
09:14:50,656 DEBUG  rekall_session         : Failed instantiating EWFAddressSpace: No base address space provided
09:14:50,656 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
09:14:50,657 DEBUG  rekall_session         : Failed instantiating WindowsCrashBMP: Must stack on another address space
09:14:50,657 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
09:14:50,658 DEBUG  rekall_session         : Failed instantiating KCoreAddressSpace: Must stack on another address space
09:14:50,658 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
09:14:50,658 DEBUG  rekall_session         : Failed instantiating WindowsCrashDumpSpace32: No base address space provided
09:14:50,658 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
09:14:50,659 DEBUG  rekall_session         : Failed instantiating WindowsCrashDumpSpace64: No base address space provided
09:14:50,659 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
09:14:50,660 DEBUG  rekall_session         : Failed instantiating Elf64CoreDump: Must stack on another address space
09:14:50,660 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
09:14:50,660 DEBUG  rekall_session         : Failed instantiating LimeAddressSpace: Must be layered on another address space.
09:14:50,660 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
09:14:50,667 DEBUG  rekall_session         : Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
09:14:50,667 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
09:14:50,668 DEBUG  rekall_session         : Failed instantiating MACHOCoreDump: Header signature invalid
09:14:50,668 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
09:14:50,668 DEBUG  rekall_session         : Failed instantiating VMemAddressSpace: Only VMEM files supported.
09:14:50,668 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
09:14:50,669 DEBUG  rekall_session         : Failed instantiating EWFAddressSpace: EWF signature not present
09:14:50,669 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
09:14:50,669 DEBUG  rekall_session         : Failed instantiating WindowsCrashBMP: Header signature invalid
09:14:50,669 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
09:14:50,670 DEBUG  rekall_session         : Failed instantiating KCoreAddressSpace: Header signature invalid
09:14:50,670 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
09:14:50,670 DEBUG  rekall_session         : Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
09:14:50,670 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
09:14:50,671 DEBUG  rekall_session         : Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
09:14:50,671 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
09:14:50,671 DEBUG  rekall_session         : Failed instantiating Elf64CoreDump: Header signature invalid
09:14:50,671 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
09:14:50,672 DEBUG  rekall_session         : Failed instantiating LimeAddressSpace: Invalid Lime header signature
09:14:50,672 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
09:14:50,672 DEBUG  rekall_session         : Failed instantiating AFF4AddressSpace: Must stack on another address space
09:14:50,672 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
09:14:50,673 DEBUG  rekall_session         : Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
09:14:50,673 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
09:14:50,673 DEBUG  rekall_session         : Failed instantiating FileAddressSpace: Must be first Address Space
09:14:50,673 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
09:14:50,674 DEBUG  rekall_session         : Failed instantiating MmapFileAddressSpace: Must be first Address Space
09:14:50,674 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
09:14:50,675 DEBUG  rekall_session         : Failed instantiating VTxPagedMemory: No more EPTs specified
09:14:50,675 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
09:14:50,676 DEBUG  rekall_session         : Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
09:14:50,676 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
09:14:50,676 DEBUG  rekall_session         : Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
09:14:50,676 INFO   rekall_session         : Autodetected physical address space AFF4AddressSpace
09:14:50,686 DEBUG  rekall_session         : Will detect profile using these Detectors: nt_index,rsds,pe,windows_kernel_file,linux,osx
09:14:50,686 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/inventory.gz
09:14:50,701 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/nt/eprocess_index.gz
09:14:50,712 INFO   rekall_session         : Loaded profile nt/eprocess_index from Directory:/rekall-profiles (in 0.0107300281525 sec)
09:14:50,712 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/nt/index.gz
09:14:50,723 INFO   rekall_session         : Loaded profile nt/index from Directory:/rekall-profiles (in 0.011246919632 sec)
09:14:50,724 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/pe.gz
09:14:50,737 INFO   rekall_session         : Loaded profile pe from Directory:/rekall-profiles (in 0.0130879878998 sec)
09:14:50,737 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/OSX/index.gz
09:14:50,738 INFO   rekall_session         : Loaded profile OSX/index from Directory:/rekall-profiles (in 0.000585079193115 sec)
09:14:50,738 DEBUG  rekall_session         : Trying method pe, offset 0
09:14:50,740 DEBUG  rekall_session         : Trying method windows_kernel_file, offset 0
09:14:50,741 DEBUG  rekall_session         : Trying method rsds, offset 0
09:14:50,846 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/nt/GUID/3844DBB920174967BE7AA4A2C20430FA2.gz
09:14:50,951 INFO   rekall_session         : Added aff4://6856d902-4845-469d-8a5b-3a75f9c452d9/PhysicalMemory as physical memory
09:14:50,971 DEBUG  rekall_session         : Succeeded instantiating AFF4AddressSpace
09:14:50,971 DEBUG  rekall_session         : Voting round with base: AFF4AddressSpace
09:14:50,971 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
09:14:50,984 DEBUG  rekall_session         : Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
09:14:50,984 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
09:14:50,984 DEBUG  rekall_session         : Failed instantiating MACHOCoreDump: Header signature invalid
09:14:50,984 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
09:14:50,984 DEBUG  rekall_session         : Failed instantiating VMemAddressSpace: Only VMEM files supported.
09:14:50,985 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
09:14:50,985 DEBUG  rekall_session         : Failed instantiating EWFAddressSpace: EWF signature not present
09:14:50,985 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
09:14:50,986 DEBUG  rekall_session         : Failed instantiating WindowsCrashBMP: Header signature invalid
09:14:50,986 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
09:14:50,986 DEBUG  rekall_session         : Failed instantiating KCoreAddressSpace: Header signature invalid
09:14:50,986 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
09:14:50,987 DEBUG  rekall_session         : Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
09:14:50,987 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
09:14:50,987 DEBUG  rekall_session         : Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
09:14:50,987 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
09:14:50,988 DEBUG  rekall_session         : Failed instantiating Elf64CoreDump: Header signature invalid
09:14:50,988 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
09:14:50,988 DEBUG  rekall_session         : Failed instantiating LimeAddressSpace: Invalid Lime header signature
09:14:50,988 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
09:14:50,989 DEBUG  rekall_session         : Failed instantiating AFF4AddressSpace: Must stack on another address space
09:14:50,989 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
09:14:50,989 DEBUG  rekall_session         : Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
09:14:50,989 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
09:14:50,990 DEBUG  rekall_session         : Failed instantiating FileAddressSpace: Must be first Address Space
09:14:50,990 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
09:14:50,990 DEBUG  rekall_session         : Failed instantiating MmapFileAddressSpace: Must be first Address Space
09:14:50,990 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
09:14:50,991 DEBUG  rekall_session         : Failed instantiating VTxPagedMemory: No more EPTs specified
09:14:50,991 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
09:14:50,992 DEBUG  rekall_session         : Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
09:14:50,992 DEBUG  rekall_session         : Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
09:14:50,992 DEBUG  rekall_session         : Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
09:14:50,992 INFO   rekall_session         : Autodetected physical address space AFF4AddressSpace
09:14:51,002 DEBUG  rekall_session         : Will detect profile using these Detectors: nt_index,rsds,pe,windows_kernel_file,linux,osx
09:14:51,002 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/inventory.gz
09:14:51,017 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/nt/eprocess_index.gz
09:14:51,028 INFO   rekall_session         : Loaded profile nt/eprocess_index from Directory:/rekall-profiles (in 0.0113899707794 sec)
09:14:51,029 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/nt/index.gz
09:14:51,043 INFO   rekall_session         : Loaded profile nt/index from Directory:/rekall-profiles (in 0.0141091346741 sec)
09:14:51,043 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/pe.gz
09:14:51,056 INFO   rekall_session         : Loaded profile pe from Directory:/rekall-profiles (in 0.0127770900726 sec)
09:14:51,056 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/OSX/index.gz
09:14:51,057 INFO   rekall_session         : Loaded profile OSX/index from Directory:/rekall-profiles (in 0.000566959381104 sec)
09:14:51,057 DEBUG  rekall_session         : Trying method pe, offset 0
09:14:51,059 DEBUG  rekall_session         : Trying method windows_kernel_file, offset 0
09:14:51,060 DEBUG  rekall_session         : Trying method rsds, offset 0
09:14:51,163 DEBUG  rekall_session         : Opened local file /rekall-profiles/v1.0/nt/GUID/3844DBB920174967BE7AA4A2C20430FA2.gz
09:14:51,196 INFO   rekall_session         : Loaded profile nt/GUID/3844DBB920174967BE7AA4A2C20430FA2 from Directory:/rekall-profiles (in 0.349620103836 sec)
09:14:51,214 INFO   rekall_session         : Detected ntkrnlmp.pdb with GUID 3844DBB920174967BE7AA4A2C20430FA2
09:14:51,214 INFO   rekall_session         : Detection method rsds yielded profile <AMD64 profile nt/GUID/3844DBB920174967BE7AA4A2C20430FA2 (Nt)>
09:14:51,215 DEBUG  rekall_session         : Running plugin (malfind) with args (()) kwargs ({})
09:14:51,496 INFO   rekall_session         : Loaded profile nt/GUID/3844DBB920174967BE7AA4A2C20430FA2 from Directory:/rekall-profiles (in 0.333714962006 sec)
09:14:51,513 INFO   rekall_session         : Detected ntkrnlmp.pdb with GUID 3844DBB920174967BE7AA4A2C20430FA2
09:14:51,513 INFO   rekall_session         : Detection method rsds yielded profile <AMD64 profile nt/GUID/3844DBB920174967BE7AA4A2C20430FA2 (Nt)>
09:14:51,514 DEBUG  analyzer         : Evidence zlip_physical_withpagefile.aff4 is a windows memory dump.
09:14:51,514 DEBUG  analyzer         : Running plugin malfind with args {} on zlip_physical_withpagefile.aff4
09:14:51,514 DEBUG  rekall_session         : Running plugin (malfind) with args (()) kwargs ({})

Notice that `analyzer` is another logger defined the same way and becoming more verbose.

**Comment by scudette** [comment]
In your code you are creating a new logger for rekall and setting it's
verbosity to debug. This is what will be used, even though the root loger
is set to Info.

The first call to basicConfig configures the root logger, and the getLogger
is making a new sublogger for rekall. This is independent to the root
logger and by setting it's level to debug all rekall messages at debug
level will be passed to the handlers. Try to set the level of the rekall
logger to info.
Am 28.02.2016 00:21 schrieb "JohnnieWalker16" <notifications@github.com>:

**Comment by JohnnieWalker16** [comment]
Notice that only the file handler is set to debug, the stream is set to INFO.

**Comment by parkisan** [comment]
But you do:

_log.setLevel(logging.DEBUG)


?

**Comment by JohnnieWalker16** [comment]
parkisan, that's how the Iogging cookbook instructs. 
Without this the logger wI'll not log debug logs on any handler. 

Changed the code a bit for it so it will be easier to figure out:


logger = logging.getLogger(name)

if len(logger.handlers) > 1: # Logger already created
	return logger

logger.setLevel(logging.DEBUG)
fmt = logging.Formatter("%(asctime)s %(levelname)-8s %(name)-27s: %(message)s")

file_handler = logging.FileHandler(filename="logger.log", mode="a")
file_handler.setLevel(logging.DEBUG)
file_handler.setFormatter(fmt)
logger.addHandler(file_handler)

stream_handler = logging.StreamHandler(sys.stdout)
stream_handler.setLevel(logging.WARNING)
stream_handler.setFormatter(fmt)
logger.addHandler(stream_handler)

logger.debug("Test")

from rekall import plugins # DO NOT remove plugins, it has a job!
from rekall.plugins.renderers import data_export
from rekall import session as rekall_session

logger.debug("Test0")
logger.error("Test2")

rekall_session.Session(filename=evidence, logger=logger)

What I got from console was 

DEBUG:logger:Test0
2016-02-29 16:53:16,114 ERROR    logger                  : Test2
ERROR:logger:Test2
DEBUG:other_logger:###################################################
DEBUG:other_logger:Created 4 processes.
DEBUG:other_logger:AYDAYADYAYADA
DEBUG:other_logger:zlip_physical_withpagefile.aff4 is being analysed in process worker-0.
DEBUG:logger:Voting round with base: None
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:logger:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:logger:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:logger:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:logger:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:logger:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
DEBUG:logger:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
DEBUG:logger:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
DEBUG:logger:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:logger:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
DEBUG:logger:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:logger:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
INFO:logger:Added aff4://6856d902-4845-469d-8a5b-3a75f9c452d9/PhysicalMemory as physical memory

And in the log file I got

2016-02-29 16:53:15,646 DEBUG    logger                  : Test
2016-02-29 16:53:16,113 DEBUG    logger                  : Test0
2016-02-29 16:53:16,114 ERROR    logger                  : Test2
2016-02-29 16:53:16,122 DEBUG    other_logger                 : ###################################################
2016-02-29 16:53:16,130 DEBUG    other_logger                 : Created 4 processes.
2016-02-29 16:53:16,130 DEBUG    other_logger                 : Object based on BaseServer was created.
2016-02-29 16:56:33,288 DEBUG    other_logger                 : zlip_physical_withpagefile.aff4 is being analysed in process worker-0.
2016-02-29 16:56:33,308 DEBUG    logger                  : Voting round with base: None
2016-02-29 16:56:33,308 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2016-02-29 16:56:33,308 DEBUG    logger                  : Failed instantiating VMSSAddressSpace: No base address space provided
2016-02-29 16:56:33,309 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2016-02-29 16:56:33,316 DEBUG    logger                  : Failed instantiating MACHOCoreDump: Must stack on another address space
2016-02-29 16:56:33,317 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2016-02-29 16:56:33,317 DEBUG    logger                  : Failed instantiating VMemAddressSpace: No base address space provided
2016-02-29 16:56:33,317 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2016-02-29 16:56:33,318 DEBUG    logger                  : Failed instantiating EWFAddressSpace: No base address space provided
2016-02-29 16:56:33,318 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2016-02-29 16:56:33,319 DEBUG    logger                  : Failed instantiating WindowsCrashBMP: Must stack on another address space
2016-02-29 16:56:33,319 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2016-02-29 16:56:33,320 DEBUG    logger                  : Failed instantiating KCoreAddressSpace: Must stack on another address space
2016-02-29 16:56:33,320 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2016-02-29 16:56:33,321 DEBUG    logger                  : Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2016-02-29 16:56:33,321 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2016-02-29 16:56:33,321 DEBUG    logger                  : Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2016-02-29 16:56:33,321 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2016-02-29 16:56:33,322 DEBUG    logger                  : Failed instantiating Elf64CoreDump: Must stack on another address space
2016-02-29 16:56:33,322 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2016-02-29 16:56:33,322 DEBUG    logger                  : Failed instantiating LimeAddressSpace: Must be layered on another address space.
2016-02-29 16:56:33,323 DEBUG    logger                  : Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2016-02-29 16:56:33,550 INFO     logger                  : Added aff4://6856d902-4845-469d-8a5b-3a75f9c452d9/PhysicalMemory as physical memory
2016-02-29 16:56:33,566 DEBUG    other_logger                 : zlip_pte_withpagefile.aff4 is being analysed in process worker-1.
2016-02-29 16:56:33,571 DEBUG    logger                  : Succeeded instantiating AFF4AddressSpace
2016-02-29 16:56:33,571 DEBUG    logger                  : Voting round with base: AFF4AddressSpace

other_logger was defined exactly the same as logger was.

Notice that the first test log didn't appear on console at all, and that the third test appeared twice, once with my format and the other without. 
my only assumption in that something inside the rekall code has something to do with the stream handler (of all loggers somehow).

**Comment by parkisan** [comment]
Johnnie, I've been looking into it and the root logger has a default
streamhandler with a logging level of NOTSET.
Even if you set logging.basicConfig(level=X), the handler has NOTSET.

You can check by doing logging.getLogger().handlers[0].level

If you do logging.debug("bla") you won't get the message through because
it's logging the one that doesn't pass it to the handler.
But logger.debug("bla") passes it upwards and gets to the upper handler,
which outputs to the console.

You can inhibit this explicitly by changing the root handler
(logging.getLogger().handlers[0].setLevel(logging.WARN)... don't think this
is the route) OR you can simply set logger.propagate = True so it never
gets to the root handler. Then you can control precisely what's outputted
to the console via your StreamHandler.

**Comment by JohnnieWalker16** [comment]
Logger.propagate = False did the trick. Thanks!
