### ISSUE TITLE
Error in check_idt plugin 

### ISSUE THREAD

**Issue by JohnnieWalker16** [google/rekall#120]
Hi,

When running some plugins against an Ubuntu server image, tried running the check_idt plugin which raised
`NameError: global name 'func' I'd not defined`

Which originated in [the plugin's module](https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/linux/check_idt.py) line 91:
`symbol=",".join(self.session.address_resolver.format_address(func.obj_offset))`

`func` wasn't defined anywhere in the plugin.

**Comment by parkisan** [comment]
https://codereview.appspot.com/289270043/

**Comment by parkisan** [comment]
This should now be fixed in head. Let me know if it's still breaking for you.
