### ISSUE TITLE
psscan fails on aff4, works on raw memory file

### ISSUE THREAD

**Issue by querist** [google/rekall#121]
psscan is failing to report anything when run on an aff4 file but works when run on the raw memory file extracted from that aff4 file. It produces the column headers but no results.
[error.txt](https://github.com/google/rekall/files/146878/error.txt)

Attaching result from running with -v

**Comment by querist** [comment]
Strangeness abounds - it worked with a different aff4 file. Please consider this low priority for now. I suspect it's a quirk with my installation. Thanks.

**Comment by parkisan** [comment]
Thanks for the report either way, querist. Perhaps there's a bug in AFF4 that we haven't tracked down yet.

Let us know if you find this again and can share the image with us.

**Comment by querist** [comment]
OK. I'll do that if it happens again. Thanks for your help.

**Comment by scudette** [comment]
According to the logs it can't contact the profile repository so it falls
back to using cached data. That might have something to do with it?

Can you try again with --cache memory this will force it to use non
persistent memory only cache.
Am 25.02.2016 5:19 nachm. schrieb "querist" <notifications@github.com>:
