### ISSUE TITLE
The 'ipython>=3.0.0' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by noorkaximi** [google/rekall#128]
i have installed rekall but get error when type 
root@noor-HP-ENVY-m6-Notebook-PC:~# rekall

> Traceback (most recent call last):
>   File "/usr/local/bin/rekall", line 9, in <module>
>     load_entry_point('rekall-core==1.4.1', 'console_scripts', 'rekall')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
>     return self.resolve()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.4.1-py2.7.egg/rekall/rekal.py", line 40, in <module>
>     entry_point.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2354, in load
>     self.require(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2371, in require
>     items = working_set.resolve(reqs, env, installer)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'ipython>=3.0.0' distribution was not found and is required by the application
>

**Comment by scudette** [comment]
If you manually install a different version of ipython after you install Rekall (even if it is a dependency of something else), PIP will downgrade it - even if it is required for currently installed applications. Applications which need a newer version of ipython will simply break just like you show.

You can easily fix it by installing ipython again:
```
pip install ipython==3.0.0
```

Just FYI, current git head is using ipython 4.0.0. 

Also you are trying to install Rekall to the system python (/usr/lib) and this is not really recommended.  In fact the current Rekall head will issue a warning when a user does not install into a virtual env. This is not really a supported configuration (although it would probably work). There are many small issues mainly around version compatibility that arise when you do not use virtualenv (such as the one you reported).

**Comment by scudette** [comment]
Please re-open if you still have issues with the current release.
