### ISSUE TITLE
DataExportRenderer output is wrong

### ISSUE THREAD

**Issue by grrrrrrrrr** [google/rekall#134]
When testing the yarascan plugin I noticed that the output is wrong - the DataExportRenderer wrongly uses cached values. Minimal example to reproduce (on my machine):

with data_export.DataExportRenderer(session=session).start() as renderer:
    utils.WriteHexdump(renderer, ("%d" * 16 * 2) % tuple(range(16 * 2)))

This gives for me:
 [u'r',
  {u'data': u'0123456789101112',
   u'hex': u'30 31 32 33 34 35 36 37 38 39 31 30 31 31 31 32',
   u'offset': 0}],
 [u'r',
  {u'data': u'1314151617181920',
   u'hex': u'31 33 31 34 31 35 31 36 31 37 31 38 31 39 32 30',
   u'offset': 16}],
 [u'r',
  {u'data': u'0123456789101112',
   u'hex': u'30 31 32 33 34 35 36 37 38 39 31 30 31 31 31 32',
   u'offset': 32}],
 [u'r', {u'data': u'293031', u'hex': u'1314151617181920', u'offset': 48}],

Notice that 21-28 is replaced with the cached value generated earlier (0-12).

The problem is that the renderer uses id() of a string as a cache key. Id is guaranteed to be unique but only during the lifetime of the string. The cache does not contain that string, it contains an encoded version so Python might reuse the id.

https://github.com/google/rekall/blob/master/rekall-core/rekall/ui/json_renderer.py#L375

**Comment by scudette** [comment]
This has been fixed.
