### ISSUE TITLE
1.4.1 failing to execute on 2008 Server Enterprise SP1 (6.1.7601)

### ISSUE THREAD

**Issue by dsweet04** [google/rekall#141]
Getting errors for "The application has failed to start because its side-by-side configuration is incorrect" when running Rekall version 1.4.1 x64 in any way on Windows Server 2008 (build 6.1.7601). 

<img width="757" alt="screen shot 2016-04-25 at 4 18 50 pm" src="https://cloud.githubusercontent.com/assets/5368247/14797595/891cc410-0b01-11e6-8321-57f6e0fb6a7e.png">

**Comment by jamesbond112** [comment]
This is the same for Vista 64 bit. Try installing Visual C++ Redist 2008. Worked for me. If you read the event logs after tracing the execution using sxstrace.exe you'll see the culprit.

**Comment by dsweet04** [comment]
We are running the binary with "--live" on systems throughout large scale (think 100k+ systems) environments. We can't install anything new on the systems such as Visual C++ Redist 2008 without a long processes and especially not during an incident.

**Comment by jamesbond112** [comment]
Might be worth upgrading your servers then ;)

**Comment by dsweet04** [comment]
Not our systems unfortunately.

**Comment by scudette** [comment]
I looked at the file with depends.exe (dependency walker) and it says that it needs msvcr90.dll which is also included with the package. AFAIK we package the runtime with Rekall to avoid this very problem (runtime not installed).

I will try to install a similar system and see if there is more to it. Is it possible for you to run the suggested sxstrace.exe on the command?

http://ntcoder.com/bab/2014/02/27/troubleshooting-side-by-side-issues-using-sxstrace/

**Comment by scudette** [comment]
I tried on a Windows 2008 Datacenter version 6.0 (build 6002) VM (AIM ID Windows_Server-2008-SP2-English-64Bit-Base-2016.04.13 (ami-af5446c5)) from EC2 and it worked without a problem. I also tried on Windows 2008 R2 (Windows_Server-2008-R2_SP1-English-64Bit-Base-2016.04.13 (ami-b95446d3)) and that worked.

I dont seem to be able to replicate this issue.

Note that the current 1.5.0 windows build was broken somehow so I pulled it off until I can rebuild it. Maybe we can try to re-test with the next build? I hope to have it out sometime today.

**Comment by dsweet04** [comment]
Here is the WinSxs Trace output  [rekall_sxs_trace.log.txt](https://github.com/google/rekall/files/242868/rekall_sxs_trace.log.txt)

**Comment by scudette** [comment]
Hi Daniel,
  Thanks so much for helping us trace this! I think I found some information that clarifies matters here:

http://blog.kalmbachnet.de/?postid=80

I verified that if one removes the public key id in the main application manifest than SXS will be forced to only search in the local directory. But then we have to have exactly the same version in the Microsoft.VC90.CRT.Manifest for it to work and also remove its public key id:

1. Remove  publicKeyToken="1fc8b3b9a1e18e3b" in both manifest files.
2. Make version="9.0.30729.9158" in rekall.exe.manifest

Can you please test that this fixes your issue? I will incorporate these modifications into the build process.

**Comment by dsweet04** [comment]
We were unable to test this on the system.

**Comment by scudette** [comment]
If you have other issues, please re-open. At this point its really hard for us to replicate and win2008 is known to have flakey sxs implementation.
