### ISSUE TITLE
winpmem only captures the default "C:\\pagefile.sys"

### ISSUE THREAD

**Issue by abdultz** [google/rekall#146]
Windows support creating pagefile.sys on multiple volumes
By default it only exists in c:\\
The path has been statically set in winpmem\executable\main.cpp on Line 92
There should be a support for acquiring multiple pagefile, if available
or atleast the command line argument should support multiple pagefile locations
as many people split pagefile across multiple hard drives which is also recommended by Microsoft
https://support.microsoft.com/en-us/kb/99768

A list of pagefiles on the system is also available from the registry
HKLM\System\CurrentControlSet\Control\Session Manager\Memory Management\PagingFiles registry value
https://blogs.technet.microsoft.com/askperf/2007/12/14/what-is-the-page-file-for-anyway/

**Comment by scudette** [comment]
Are you saying that the -p option does not work for you?

```
C:\Users\mic>winpmem-2.1.post3.exe -h

USAGE:

   winpmem-2.1.post3.exe  [-l] [-u] [--write-mode] [--mode <MmMapIoSpace,
                          PhysicalMemory, PTERemapping>] [--driver <Path to
                          driver.>] [--format <map, elf, raw>] [-m] [-p
                          </path/to/pagefile>] ...  [-V] [-d] [-v] [-t] [-i
                          </path/to/file/or/device>] ...  [-e <string>] [-o
                          </path/to/file>] [-c <zlib, snappy, none>] [--]
                          [--version] [-h] </path/to/aff4/volume> ...
...

   -p </path/to/pagefile>,  --pagefile </path/to/pagefile>  (accepted
      multiple times)
     Also capture the pagefile. Note that you must provide this option
     rather than e.g. '--input c:\pagefile.sys' because we can not normally
     read the pagefile directly. This option will use the sleuthkit to read
     the pagefile.

...
   The WinPmem memory imager.  Copyright 2014 Google Inc.

```

**Comment by abdultz** [comment]
I am using pmem 1.6.2 (winpmem.rc). Compiled winpmem myself from the source 
I have 16GB RAM in my computer and two pagefiles (16GB residing in c:\ and another 16GB residing in e:\)
As per your reply I ran using the following command:
winpmem.exe -p c:\pagefile.sys -p e:\pagefile.sys abcd.mem
The resulting file is 16.7 GB in size

Also I tested it on a 32 bit system having 4GB RAM and 
2 x pagefile.sys (~3.3GB) residing on different volumes.
The resultant file is always 3.24GB in size

Is that correct? I dont have sleuthkit installed...

**Comment by scudette** [comment]
Winpmem 1.6.2 is the old version. We still keep it around because it's very
stable and has been used for years with no problems.

You can try the latest release 2.1 which supports multiple page files among
other features. If you want to build it from source it is the one in the
rekall/tools/pmem directory.

**Comment by scudette** [comment]
There is more information here:
http://rekall-forensic.blogspot.ch/2016/05/the-pmem-suite-of-memory-acquisition.html

Please re-open if you still have issues.
