### ISSUE TITLE
Upgrading from 1.4.1 to 1.5.1: 'efilter' version mismatch

### ISSUE THREAD

**Issue by diogo-fernan** [google/rekall#149]
Getting the following error with `sudo pip install rekall --upgrade` on a SIFT 3 workstation:

> Downloading/unpacking efilter==1!1.2 (from rekall-core>=1.5.0->rekall)
>   Could not find a version that satisfies the requirement efilter==1!1.2 (from rekall-core>=1.5.0->rekall) (from versions: 1449128552, 1, 1449139184, 1438631774, 1453815385, 1438631350, 1446301913, 1440489265, 1, 1445943458, 1438555278, 1450268920, 1, 1438554658, 1438624661, 1%211.2, 1445495565, 1438555622, 1445494810, 1-1.0)
> Cleaning up...
> No distributions matching the version for efilter==1!1.2 (from rekall-core>=1.5.0->rekall)

Is it the '1%211.2' on the version list?

Thanks,
Diogo

**Comment by scudette** [comment]
What is your command line? Are you using the official pypi or the rekall
index?

Is it possible that pip is to old? Can you please try to upgrade pip first?

Pip install --upgrade pip

Thanks
Michael

**Comment by diogo-fernan** [comment]
I did have an outdated `pip` version from some reason.

Anyway, issuing `pip install rekall` on a newly built SIFT workstation yields the error below. The SIFT `bootstrap.sh` method fails to install Rekall, hence the manual installation attempt. Opened issue #109 on SIFT too: https://github.com/sans-dfir/sift/issues/109.

```
$ python --version
Python 2.7.6
$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
$ sudo pip install rekall
Collecting rekall
  Using cached rekall-1.5.1.zip
Collecting rekall-core>=1.5.0 (from rekall)
  Using cached rekall-core-1.5.1.zip
    Complete output from command python setup.py egg_info:
    *****************************************************
      WARNING: You are not installing Rekall in a virtual
      environment. This configuration is not supported!!!
      Expect breakage.
    *****************************************************
    error in rekall-core setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6CicIr/rekall-core/
```

**Comment by scudette** [comment]
Hi Diogo,
  This time it is complaining about a couple of things:

-  you are not installing into a virtualenv - this is not really
supported. You should try this first:

virtualenv /some/dir/
source /some/dir/bin/activate

pip install --upgrade pip setuptools
pip install rekall

It looks like your python version is very old - you should try to
install anything above 2.7.9. The current version is 2.7.11

Thanks
Michael.

**Comment by diogo-fernan** [comment]
I installed Python v2.7.11 and created a virtual environment, which resolved the issue.
However, is there a way to make that environment system-wide without having to source and without the virtual environment prefix on the terminal prompt?

**Comment by scudette** [comment]
I think it should work if you just install to the system, providing you use a recent version of python, but this setup is not really supported because then rekall's dependencies are getting mixed up in the system. Virtual envs are the standard for python code.

Note that if you create a virtual env somewhere (anywhere you want) you can just symlink the binaries in that and it will automatically enter the virtualenv when you run it. For example here on the mac I am using a different version of python than Apple ships (found in /opt):

```
$ virtualenv -p /opt/local/bin/python2.7 /tmp/3/       <---- Path to my virtualenv
Running virtualenv with interpreter /opt/local/bin/python2.7
New python executable in /tmp/3/bin/python
Installing setuptools, pip, wheel...done.

$ source /tmp/3/bin/activate
(3) $ pip install rekall
Collecting rekall
  Downloading rekall-1.5.1.zip (2.9MB)
    100% |████████████████████████████████| 2.9MB 437kB/s
Collecting rekall-core>=1.5.0 (from rekall)
...

(3) $ deactivate      <---- I am exiting the virtual env now.
$ /tmp/3/bin/rekal    <---- Note that now I am running the binary from the virtualenv without being in the virtual env.

----------------------------------------------------------------------------
The Rekall Memory Forensic framework 1.5.1 (Furka).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------
[1] Default session 10:31:08>
```

**Comment by diogo-fernan** [comment]
I was not aware of this virtual environment concept before. Thanks Michael!
