### ISSUE TITLE
vtop pml4e is always 0x0

### ISSUE THREAD

**Issue by multivac3834** [google/rekall#151]
hello,
OS is windows 10 pro(10.0.10586 Build 10586). it worked 1 time and now its always failing. on my VM(Hyper-V win10pro) its succeeds every time.

I already reinstalled rekall, python and  deleted ".rekall_cache" folder

[session.txt](https://github.com/google/rekall/files/292615/session.txt)
[test_mem.txt](https://github.com/google/rekall/files/292618/test_mem.txt)

**Comment by scudette** [comment]
I suspect this is related to the new windows 10 compressed memory support:

https://channel9.msdn.com/Blogs/Seth-Juarez/Memory-Compression-in-Windows-10-RTM

Its great that you have replicated this with a test case. I will try your code and see if I can replicate the same thing.

**Comment by multivac3834** [comment]
vad(7588)
2016-06-01 07:16:55,528:DEBUG:rekall.1:Running plugin (vad) with args ((7588,)) kwargs ({})
2016-06-01 07:16:55,561:DEBUG:rekall.1:Listed 79 processes using PsActiveProcessHead
2016-06-01 07:16:56,006:DEBUG:rekall.1:Listed 71 processes using CSRSS
2016-06-01 07:16:57,010:DEBUG:rekall.1:Listed 79 processes using PspCidTable
2016-06-01 07:16:57,039:DEBUG:rekall.1:Listed 77 processes using Sessions
2016-06-01 07:16:57,091:DEBUG:rekall.1:Listed 74 processes using Handles
**************************************************
Pid: 7588 text_mem.exe
     VAD       lev   Start Addr      End Addr     com   ------- ------       Protect        Filename
-------------- --- -------------- -------------- ------                -------------------- --------
0xe00084152260   4 0x000000010000 0x00000001ffff      0 Mapped         READWRITE
0xe0007fec0730   3 0x000000030000 0x000000044fff      0 Mapped         READONLY
0xe00085077d50   2 0x000000050000 0x00000008ffff     11 Private        READWRITE
0xe00083d463e0   4 0x000000090000 0x00000018ffff      5 Private        READWRITE
0xe000839ee800   3 0x000000190000 0x000000193fff      0 Mapped         READONLY
0xe00083ab55b0   1 0x0000001a0000 0x0000001a0fff      0 Mapped         READONLY
0xe00081ef9f40   4 0x0000001b0000 0x0000001b1fff      2 Private        READWRITE
0xe00082a5b090   3 0x000000200000 0x0000003fffff      5 Private        READWRITE
0xe000857ed420   4 0x000000400000 0x0000004bdfff      0 Mapped         READONLY             \Windows\System32\locale.nls
0xe00087418330   2 0x000000580000 0x00000058ffff      5 Private        READWRITE
0xe00087453120   3 0x000000f40000 0x000000f4dfff      1 Private        READWRITE
0xe00084121750   0 0x000000f90000 0x000000fc9fff      4 Mapped  Exe    EXECUTE_WRITECOPY    \Users\kai\Desktop\text_mem.exe
0xe000839b4d40   5 0x000001030000 0x00000103ffff      3 Private        READWRITE
0xe00081f2db50   4 0x0000010e0000 0x0000011dffff     29 Private        READWRITE
0xe00083a7e640   5 0x00005c980000 0x00005c9cffff      5 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\System32\wow64.dll
0xe00083cda010   3 0x00005c9d0000 0x00005c9d7fff      2 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\System32\wow64cpu.dll
0xe0008335e8f0   5 0x00005c9e0000 0x00005ca59fff      4 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\System32\wow64win.dll
0xe00087347d00   4 0x000074180000 0x000074189fff      3 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\cryptbase.dll
0xe00084e168a0   5 0x000074190000 0x0000741adfff      2 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\sspicli.dll
0xe000833c44d0   2 0x0000742e0000 0x0000743bffff      3 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\kernel32.dll
0xe0008723a4e0   4 0x000075090000 0x00007514dfff      7 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\msvcrt.dll
0xe0008842b120   5 0x000075370000 0x00007541cfff      3 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\rpcrt4.dll
0xe00084abf290   3 0x0000754b0000 0x00007562dfff      6 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\KernelBase.dll
0xe00084926eb0   5 0x000075ba0000 0x000075be3fff      5 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\sechost.dll
0xe0007fec0bd0   4 0x000077040000 0x0000770bafff      6 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\advapi32.dll
0xe000849b0280   5 0x0000770e0000 0x000077137fff      2 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\bcryptprimitives.dll
0xe0008450f190   1 0x000077460000 0x0000775dafff      7 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\SysWOW64\ntdll.dll
0xe00088463b90   4 0x00007f460000 0x00007f55ffff      0 Mapped         READONLY
0xe00083460720   3 0x00007f560000 0x00007f582fff      0 Mapped         READONLY
0xe00085ad3110   2 0x00007ffe0000 0x00007ffeffff     -1 Private        READONLY
0xe0008866a290   4 0x00007fff0000 0x7ffedfcdffff     -1 Private        READONLY
0xe00087377c90   3 0x7ffedfce0000 0x7ffedfea0fff     13 Mapped  Exe    EXECUTE_WRITECOPY    \Windows\System32\ntdll.dll
0xe000885ca8f0   4 0x7ffedfea1000 0x7ffffffeffff     -1 Private        READONLY
         Out<3> Plugin: vad

**Comment by scudette** [comment]
In your output there is nothing mapped at address 0x654880. Why do you expect that vtop 0x654880 be valid?

**Comment by multivac3834** [comment]
sry thats a new run of my program
![dump](https://cloud.githubusercontent.com/assets/17825129/15699055/63668978-27ca-11e6-8d73-d2087c795cfa.jpg)

**Comment by scudette** [comment]
So I tried using your code and I can not replicate an issue. First I noticed a small bug in your code which I fixed below - it would always overwrite with 0 because cin.get() delivers 2 chars minimum (the selection e.g. 1 and a carriage return). 

Next I ran cc(pid) as you did and dump (virtual address) as you did and saw the expected pattern. Be aware that you may not be able to see the pattern change because Rekall is caching physical memory pages so you might need to flush the cache between each dump plugin of the same virtual address (session.physical_address_space._cache.Flush() )

```
C:\Users\mic>z:\mem_test.exe
DataAddress: 0x6c6120
Pid: 2356

[1] Default session 23:03:09> vtop 0x6c6120
----------------------------> vtop(0x6c6120)
2016-05-31 23:03:13,812:DEBUG:rekall.1:Running plugin (vtop) with args ((7102752,)) kwargs ({})

******************** 0x6c6120 ********************
Virtual 0x0000006c6120 Page Directory 0xcd50000
pml4e@ 0xcd50000 = 0xc0000037d01867
pdpte@ 0x37d01000 = 0xd0000032bc2867
pde@ 0x32bc2018 = 0x140000000bd80867
pte@ 0xbd80630 = 0xaa8000001dbe9847
[_MMPTE_HARDWARE Hard] @ 0x00000bd80630
Offset             Field              Content
------ ------------------------------ -------
  0x0    Accessed                        [BitField(5-6):Accessed]: 0x00000000
  0x0    CacheDisable                    [BitField(4-5):CacheDisable]: 0x00000000
  0x0    CopyOnWrite                     [BitField(9-10):CopyOnWrite]: 0x00000000
  0x0    Dirty                           [BitField(6-7):Dirty]: 0x00000001
  0x0    Dirty1                          [BitField(1-2):Dirty1]: 0x00000001
  0x0    Global                          [BitField(8-9):Global]: 0x00000000
  0x0    LargePage                       [BitField(7-8):LargePage]: 0x00000000
  0x0    NoExecute                       [BitField(63-64):NoExecute]: 0x00000001
  0x0    Owner                           [BitField(2-3):Owner]: 0x00000001
  0x0    PageFrameNumber                 [BitField(12-48):PageFrameNumber]: 0x0001DBE9
  0x0    SoftwareWsIndex                 [BitField(52-63):SoftwareWsIndex]: 0x000002A8
  0x0    Unused                          [BitField(10-11):Unused]: 0x00000000
  0x0    Valid                           [BitField(0-1):Valid]: 0x00000001
  0x0    Write                           [BitField(11-12):Write]: 0x00000001
  0x0    WriteThrough                    [BitField(3-4):WriteThrough]: 0x00000000
  0x0    reserved1                       [BitField(48-52):reserved1]: 0x00000000
Physical Address 0x1dbe9120

Deriving physical address from runtime physical address space:
Physical Address 0x1dbe9120
        Out<13> Plugin: vtop
[1] Default session 23:03:13> rammap 0x1dbe9120
2016-05-31 23:03:29,953:DEBUG:rekall.1:Running plugin (rammap) with args ((499028256,)) kwargs ({})
Phys Address        List          Use       Pr    Process             Name          PID        VA           Offset     Filename
---------------- ---------- --------------- -- -------------- -------------------- ----- -------------- -------------- --------
      0x1dbe9000 Active     Private         5  0xe000bfeb4640 mem_test.exe          2356       0x6c6000                 
      0x1dbea000 Active     Kernel          5                                            0xf6803748e000                 
      0x1dbeb000 Standby    Private         4  0xe000bec5a040 System                   4   0x4f035e6000                 
      0x1dbec000 Active     Mapped File     5  0xe000c0bb2780 MsMpEng.exe           1592 0x7fffb322b000        0x3a400 C:\ProgramData\Microsoft\Windows Defender\Definition Updates\{302EF4F5-E629-4E56-A899-1E2DCC170B91}\mpengine.dll
      0x1dbed000 Active     Private         5  0xe000bf6dd280 rekal.exe             3632      0xb63b000                 
      0x1dbee000 Active     Kernel          5                                            0xf8016ea99000                 
      0x1dbef000 Active     Private         5  0xe000bec5a040 System                   4   0x4f05567000                 
      0x1dbf0000 Active     Mapped File     5  0xe000c1294780 ShellExperienc        3048 0x7fffbbcfc000       0x18b400 C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\StartUI.dll
      0x1dbf1000 Active     Mapped File     5  0xe000c0f51780 sihost.exe            2080 0x7fffc138e000       0x18d000 C:\Windows\System32\CoreUIComponents.dll
      0x1dbf2000 Active     Kernel          5                                            0xf6bfffe2b000                 
        Out<14> Plugin: rammap
[1] Default session 23:03:51> ptov 0x1dbe9120
2016-05-31 23:04:03,469:DEBUG:rekall.1:Running plugin (ptov) with args ((499028256,)) kwargs ({})
DTB 0xcd50000 Owning process: 0xe000bfeb4640 mem_test.exe  2356
PML4E@ 0xcd50f68 = 0x800000000cd50863
PDPTE@ 0xcd50000 = 0xc0000037d01867
PDE@ 0x37d01000 = 0xd0000032bc2867
PTE@ 0x32bc2018 = 0x140000000bd80867
Physical Address 0x1dbe9120
Virtual Address       0x6c6120 (DTB      0xcd50000)
        Out<15> Plugin: ptov
```

```
#include <iostream>
#include <vector>
#include <process.h>

int main() {
  std::vector<unsigned int> buf;
  for (int i = 0; i < 4096; i++)
    buf.push_back(0xDEADBEEF);
  std::cout << "DataAddress: " << std::hex << buf.data() <<
      std::endl << "Pid: " << std::dec << _getpid() << std::endl;

  char sel = 0;
  bool exit = false;
  while (!exit) {
    std::cin.get(sel);
    unsigned int pattern = 0;
    switch (sel) {
      case '1': pattern = 0xffffffff; break;
      case '2': pattern = 0xCAFEBABE; break;
      case '3': pattern = 0xfafafafa; break;
      case '4': pattern = 0; break;
      case 'x': exit = !exit; break;
      default:
        continue;
    }
    std::cout << "Write Pattern:" << std::hex << pattern <<
        "@" << buf.data() << std::endl;
    for (auto &i : buf)
      i = pattern;
  }
  return 0;
}
```

**Comment by multivac3834** [comment]
I did some further research its looks like the DTB(DirBase) address is truncated to 32bit which is not an issue on a low memory environment.

in my test cases hyper-v 512mb ram rekall was always right. with 8gb ram it was always wrong.
i repeat the test with a real machine 16gb ram almost always wrong and with "bcdedit /set removememory 12288" it worked.
![krnldbg](https://cloud.githubusercontent.com/assets/17825129/16069293/952011ec-32cd-11e6-86ac-20a23df324a0.png)

because WinDbgis working correct I guess my custom profile. I build from the right pdb is also correct.

**Comment by scudette** [comment]
Ah - that is an excellent find! Very well spotted. There was in fact a very subtle bug which was left over from the old Volatility codebase. There is this code in the common overlays for windows:

```
    # The DTB is really an array of 2 ULONG_PTR but we only need the first one                                                                                
    # which is the value loaded into CR3. The second one, according to procobj.c                                                                              
    # of the wrk-v1.2, contains the PTE that maps something called hyper space.                                                                               
    '_KPROCESS' : [None, {
	'DirectoryTableBase' : [None, ['unsigned long']],
    }],
```

I think it was put there because on windows XP the DirectoryTableBase is defined like this:
```
 "DirectoryTableBase": [24, ["Array", {
    "count": 2, 
    "target": "unsigned long"
    }]], 
```

But on all later versions it is defined like this:
```
   "DirectoryTableBase": [24, ["unsigned long", {}]], 
```
or
```
   "DirectoryTableBase": [40, ["unsigned long long", {}]], 
```

I changed the overlay to define the field as an address (which means its 32 bit on x86 and 64 bit on amd64). This should fix it.

Thanks for reporting!

**Comment by scudette** [comment]
This is now fixed.
