### ISSUE TITLE
parse_pdb IO error: PDB file not supported.

### ISSUE THREAD

**Issue by raviteja7** [google/rekall#194]
Hi,
I am trying to build a custom profile for Win 10. At the parse_pdb stage, I am having this error
![image](https://cloud.githubusercontent.com/assets/2549509/19252871/343255da-8f15-11e6-9ad3-4b4dd5b9842a.png)
Thanks

**Comment by scudette** [comment]
It seems that this PDB format is not supported (It has the wrong header magic). How did you get this PDB file? Can you please share the GUID?

**Comment by raviteja7** [comment]
I used fetch_pdb to get the PDB file. Right now I don't have the GUID (I can provide it later). I did the same  on another Win10 machine and received the same error. These are the steps that I followed.

The GUID is D530E1D39E024EFF82EDB50767C75FBA1

![guid](https://cloud.githubusercontent.com/assets/2549509/19255698/a313e5cc-8f2e-11e6-9530-795b266241d9.PNG)

![fetch_pdb](https://cloud.githubusercontent.com/assets/2549509/19255701/ac9c7280-8f2e-11e6-9074-426a2cfa6e2b.PNG)

![parse_pdb](https://cloud.githubusercontent.com/assets/2549509/19255714/b89c7558-8f2e-11e6-802b-338cbab6eb55.PNG)

**Comment by scudette** [comment]
It looks like the file is corrupted? It's very small. Can you open it in a
hex editor? Note that there was a change in the ms symbol server that
required rekall to use an older user agent string very recently. So if you
are not running git head it probably won't be able to fetch the right pdb.

**Comment by scudette** [comment]
You can see that this particular GUID was added to the public repository:
https://github.com/google/rekall-profiles/blob/gh-pages/v1.0/src/nt/guids.yaml#L1101

https://github.com/google/rekall-profiles/blob/gh-pages/v1.0/nt/GUID/D530E1D39E024EFF82EDB50767C75FBA1.gz

Maybe you can just update from there?

**Comment by raviteja7** [comment]
Thanks Michael
