### ISSUE TITLE
Tutorial is missing code snippets for automating Rekall

### ISSUE THREAD

**Issue by moyix** [google/rekall#251]
The [Rekall tutorial](http://www.rekall-forensic.com/docs/Manual/tutorial.html#_automating_rekall) is missing the code snippets under the "Automating Rekall" section. The numbered bullets seem to be referring to code that actually exists somewhere, so I assume this is just something that got accidentally stripped out in some document conversion process?

**Comment by scudette** [comment]
Thanks, this has been fixed now and we moved to the new site.

http://www.rekall-forensic.com/documentation-1/rekall-documentation/tutorial
