### ISSUE TITLE
An error message during the installation 

### ISSUE THREAD

**Issue by Alammari** [google/rekall#263]
Dears,

Please help me in this issue.
I using windows 10 64 and the python is version 2.7.10, when I tried to install Rekall I got this message in the end: 

---------------------------------------------------------------------------------------------

Installed c:\users\*******\dev\lib\site-packages\rekall_core-1.6.3.dev6-py2.7.egg
Processing dependencies for rekall-core==1.6.3.dev6
Searching for rekall-lib<1.7,>=1.6.1
Reading https://pypi.python.org/simple/rekall-lib/
Couldn't find index page for 'rekall-lib' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for rekall-lib<1.7,>=1.6.1
error: Could not find suitable distribution for Requirement.parse('rekall-lib<1.7,>=1.6.1')

---------------------------------------------------------------------------------------------

Thanks and Regard.

**Comment by scudette** [comment]
I assume you are installing from git source. I updated the README.md to include the missing step. You need to install rekall-lib before you install the others.
