### ISSUE TITLE
missing rekall python API in rekall-forensic debian package

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#270]
Hi !

I would like to install Rekall on a Debian VM without internet connection.
My idea was to `scp` the latest release of Rekall, available as a debian package: 
[rekall-forensic_1.6.0_amd64.deb](https://github.com/google/rekall/releases/download/v1.6.0/rekall-forensic_1.6.0_amd64.deb)

the rekall comand line tool is working fine after the install, but i cannot import the Rekall python library.

Use this Dockerfile to verify:

~~~
FROM ubuntu:latest

RUN apt update
RUN apt-get install -y \
        python wget

RUN wget https://github.com/google/rekall/releases/download/v1.6.0/rekall-forensic_1.6.0_amd64.deb
RUN dpkg -i rekall-forensic_1.6.0_amd64.deb

ENTRYPOINT  python -c 'import rekall'
~~~

And run it.
~~~
docker build -t rekall-deb .
docker run -ti --rm=true rekall-deb
~~~

Unable to import rekall
~~~
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named rekall
~~~

I suppose this will just deploy a virtualenv with rekall command line.

-> How can i write scripts and depend on the rekall module ?
(this is the script i'm testing: [symbols.py](https://github.com/KVM-VMI/nitro/blob/8ccf9375c16033fb31fdf4c06c7d127798924dce/nitro/symbols.py))

Thank you Michael !

**Comment by Wenzel** [comment]
So i found a solution in the meantime, using pip.

You can do the following:
1. `pip download rekall`
2. `scp deps/ offline_host`
3. `pip install --no-index --find-links deps rekall`

And you have to uprade `pip`, `wheel` and `setuptools` first in the same way.

You can close this issue if you have no other comments @scudette.

Thanks.

**Comment by scudette** [comment]
Yes this is the documented way for installing pip packages offline. The only supported way to install Rekall is inside a Virtual Environment. The debian package is just a virtual environment packaged inside the deb package.

You can just activate that virtual env and then import anything inside it. So you can run your script with the python included in the rekall deb package (which is just a shortcut to activate the packaged virtual env).
