### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i1zeii5f/rekall-agent/     

### ISSUE THREAD

**Issue by fpusersuggest** [google/rekall#289]
Hi, I have the following error on Fedora26 at install:       
 
    [myusername@localhost ~]$ cd rekall/    
    [myusername@localhost rekall]$ ls       
    bin  include  lib  lib64  pip-selfcheck.json
    [myusername@localhost rekall]$ source  bin/activate                                  
    (rekall) [myusername@localhost rekall]$ pip install --upgrade setuptools pip wheel   
    Requirement already up-to-date: setuptools in ./lib/python3.6/site-packages          
    Requirement already up-to-date: pip in ./lib/python3.6/site-packages                 
    Requirement already up-to-date: wheel in ./lib/python3.6/site-packages               
    (rekall) [myusername@localhost rekall]$ pip install rekall-agent rekall              
    Collecting rekall-agent                 
      Using cached rekall_agent-1.6.0.tar.gz
        Complete output from command python setup.py egg_info:                           
        Traceback (most recent call last):  
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-i1zeii5f/rekall-agent/setup.py", line 30                  
            exec open("_version.py").read() in ENV                                       
                    ^                       
        SyntaxError: invalid syntax         
                                            
        ----------------------------------------                                         
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i1zeii5f/rekall-agent/

**Comment by scudette** [comment]
I think you are using python 3.x. this is not yet supported. We will
probably support python 3 in the next release.
