### ISSUE TITLE
rekall install failing on win10 with error about rekall-efilter

### ISSUE THREAD

**Issue by epetty100** [google/rekall#291]
I'm trying to install rekall 1.7.0rc1 on Windows 10 version 1703 (Build 15063.632) with python 2.7.14

The installation is failing with an error about rekall-efilter.  Here is the output:

```
(env-rekall) c:\Users\XXX\Downloads\rekall-master\rekall-core>python setup.py install
C:\Users\XXX\env-rekall\lib\site-packages\setuptools\dist.py:351: UserWarning: Normalizing '1.7.0.rc1' to '1.7.0rc1'
  normalized_version,
running install
...
stuff omitted for brevity
...
Installed c:\users\XXX\env-rekall\lib\site-packages\rekall_core-1.7.0rc1-py2.7.egg
Processing dependencies for rekall-core==1.7.0rc1
Searching for rekall-efilter==1.5.2
Reading https://pypi.python.org/simple/rekall-efilter/
No local packages or working download links found for rekall-efilter==1.5.2
error: Could not find suitable distribution for Requirement.parse('rekall-efilter==1.5.2')

(env-rekall) c:\Users\XXX\Downloads\rekall-master\rekall-core>
```

I'm not sure what to do at this point. I've tried googling but am coming up short.

 Here is what I've done up to this point as part of installing rekall:
⦁	Installed python 2.7.14
⦁	Installed virtualenv
⦁	Created a virtualenv for rekall
⦁	Downloaded rekall source from github
⦁	Installed rekall-lib first, per an issue reported on github
⦁	Installed Microsoft Visual C++ complier for Python 2.7
⦁	Then tried to install rekall again by running 'python setup.py install' inside the rekall-core directory, but I'm getting that above error.

How can I fix this and get rekall installed successfully?

Thanks,
Ely

**Comment by scudette** [comment]
Hi there,
  We did not upload pypi packages just yet.  You can just install it
from the github site

https://github.com/rekall-innovations/dotty

https://github.com/rekall-innovations/dotty/releases/tag/v1.5.2

Thanks
Michael.

**Comment by scudette** [comment]
Oh, I must have already uploaded the file and forgot
https://pypi.org/project/rekall-efilter/#files

I think your main issue is that you are not using pip to install. We
only upload wheels and not source package so I think you need pip to
actually install dependencies properly:

 (env-rekall) c:\Users\XXX\Downloads\rekall-master\rekall-core>pip install .

Thanks
Michael.

**Comment by epetty100** [comment]
Running "pip install ." did the trick. Thank you!
