### ISSUE TITLE
pyaff4 dependency is not properly pinned

### ISSUE THREAD

**Issue by mbushkov** [google/rekall#303]
Hi!
rekall-core depends on pyaff4 (https://github.com/google/rekall/blob/master/rekall-core/setup.py#L56). The dependency is specified as "pyaff4 >= 0.24, < 0.30". Given that current pyaff4 version is 0.26 (https://pypi.org/project/PyAFF4/#history) this effectively means that any pyaff4 update may break Rekall.

GRR currently depends on rekall-core~=1.6.0 and recent pyaff4 upgrade broke rekall-core and, consequently, our build: https://ci.appveyor.com/project/destijl/grr/build/1.0.265#L4654

Seems like it make sense to pin pyaff4 dependency to something specific to avoid breaking rekall-core in the future.

**Comment by scudette** [comment]
Yes we had to push a pyaff4 bug fix and this is why we have a range of versions. It is true that we have screwed it up a little bit here by accidentally including new features into a bug fix release :-(. The current release is pyaff4==0.26.post3 and it should work fine with Rekall 1.6.0.

Its a bit hard to read your backtrace but I think this is where it fails:
``` 
  File "site-packages\pyaff4\aff4.py", line 28, in <module>
  File "c:\users\appveyor\appdata\local\temp\1\pip-build-egeckv\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\pyaff4\rdfvalue.py", line 18, in <module>
  File "site-packages\future\standard_library\__init__.py", line 457, in install_aliases
ImportError: No module named UserList
```
So the exception is about it trying to import "UserList" which is not an aff4 class. Looking at rdfvalue line 18 (https://github.com/google/aff4/blob/master/pyaff4/pyaff4/rdfvalue.py#L18):

```
from future import standard_library
standard_library.install_aliases()
```

And install_aliases is described as "Monkey-patches the standard library in Py2.6/7 to provide aliases for better Py3 compatibility." . This this is where it fails:

```
    for (newmodname, newobjname, oldmodname, oldobjname) in MOVES:
        __import__(newmodname)
```

This code tries to import some old modules and put them in the new place so python3 code can find them. The MOVES dict looks like:

```
# (New module name, new object name, old module name, old object name)
MOVES = [('collections', 'UserList', 'UserList', 'UserList'),
         ('collections', 'UserDict', 'UserDict', 'UserDict'),
         ('collections', 'UserString','UserString', 'UserString'),
         ('itertools', 'filterfalse','itertools', 'ifilterfalse'),
         ('itertools', 'zip_longest','itertools', 'izip_longest'),
         ('sys', 'intern','__builtin__', 'intern'),
         # The re module has no ASCII flag in Py2, but this is the default.
         # Set re.ASCII to a zero constant. stat.ST_MODE just happens to be one
         # (and it exists on Py2.6+).
         ('re', 'ASCII','stat', 'ST_MODE'),
         ('base64', 'encodebytes','base64', 'encodestring'),
         ('base64', 'decodebytes','base64', 'decodestring'),
         ('subprocess', 'getoutput', 'commands', 'getoutput'),
         ('subprocess', 'getstatusoutput', 'commands', 'getstatusoutput'),
         ('subprocess', 'check_output', 'future.backports.misc', 'check_output'),
         ('math', 'ceil', 'future.backports.misc', 'ceil'),
         ('collections', 'OrderedDict', 'future.backports.misc', 'OrderedDict'),
         ('collections', 'Counter', 'future.backports.misc', 'Counter'),
         ('itertools', 'count', 'future.backports.misc', 'count'),
         ('reprlib', 'recursive_repr', 'future.backports.misc', 'recursive_repr'),
         ('functools', 'cmp_to_key', 'future.backports.misc', 'cmp_to_key'),
```

So I think this code essentially tries to import UserList and put it in collections.

I suspect what is happening here is that pyinstaller is not realizing this code exists and trims those modules out of the binary so when future tries to import them these standard modules are missing. 

I would suggest you add these standard modules to the pyinstaller spec file (or just add an explicit import for them) to make pyinstaller not trim them.

**Comment by scudette** [comment]
There seem to be other similar issues:
https://github.com/pyinstaller/pyinstaller/issues/2820

**Comment by scudette** [comment]
The usual way to fix it is to have code like this somewhere pyinstaller can find it:

```
if 0:
   import UserList, UserDict, UserString, itertools, __builtin__
   import stat, subprocess, commands
   import future.backports.misc
```

This will force pyinstaller into including this modules but they wont really be imported. Its probably worth adding this to `pyaff4` and `rekall` although the ideal place is actually in `future` or `pyinstaller`.

**Comment by scudette** [comment]
This should be fixed with https://github.com/google/aff4/commit/3e14543654a9776c6c95fc451dc7db22ea19f4d1

**Comment by scudette** [comment]
Please reopen if this does not work. Your automated build should just fix itself now.

**Comment by mbushkov** [comment]
Michael, thanks for the fix!
I have concerns about the same scenario, though: pyaff4 gets updated with some unforeseen compatibility issues with an already released rekall-core PIP package and rekall-core gets broken without being directly updated. Is there a reason why pyaff4 dependency is not pinned to a precise  version in rekall-core package?

**Comment by scudette** [comment]
Ideally we should not be releasing any new features at the same release version. In this case this was probably a mistake as I incorporated a bug fix at the same time as a major change. We should be more strict with semantic versioning (http://semver.org/).

It is important to have some flexibility for releasing bugfixes. Otherwise it is impossible to fix a bug in pyaff4 without also making a release of Rekall.

**Comment by mbushkov** [comment]
Yes, I agree that there should be some flexibility for minor bugfixes. 

I guess, there are 2 separate issues:
1. Current pyaff4 dependency spec in rekall-core seems a little strange: >= 0.26, < 0.30. It's very confusing: why the upper limit is 0.30, what does 0.30 mean in pyaff4's case? Seems like it makes sense to adopt proper semantic versioning in pyaff4 and specify the dependency as "~=0.26.0" or so.
1. If pyaff4 had a Travis setup or something similar, then even a simple Python2.7-based test would indicate the issue (naturally, there should be a Python3-based test too). Otherwise there's no way to be sure that a small bugfix won't break something upstream.

**Comment by mbushkov** [comment]
Correcting myself on 2): simple test probably wouldn't be enough, since the issue occurs in pyinstaller.

**Comment by scudette** [comment]
Yes these are all very good suggestions:
1. PyAFF4 should adopt a semantic versioning scheme and stable releases with only bug fixes going to these branches.
2. Should have automated tests on travis.

Since we are moving pyaff4 from the Google org into the AFF4 org we will be making some changes and these are very good suggestions.

Unfortunately it is hard to support pyinstaller because it is an uncommon use case and in this case, the broken package was actually future (we just implemented a hack in pyaff4 to work around pyinstaller). I am not sure we can reliably support pyinstaller in future. But if we have strict branches with bug fixes only going into them this should at least not break projects which already have gotten pyinstaller to work.

**Comment by mbushkov** [comment]
Michael, thank you for a detailed reply!
