### ISSUE TITLE
rekall error when using aff4 with snappy compression

### ISSUE THREAD

**Issue by dougkite** [google/rekall#331]
Used Winpmem-2.1.post4 to create an image with snappy compression with the following command:
winpmem-2.1.post4.exe -t -c snappy -o test.aff4

When I try to open the image with rekall 1.7.1, it gives an error related to compression. 

If I create the image with zlib compression, rekall can read the image. 

I used pip to install python-snappy into the virtualenv. 

Key error seems to be as follows (full output below):
/tmp/MyEnv/lib/python3.6/site-packages/pyaff4/aff4_image.py in _ReadChunkFromBevy(self, chunk_id, bevy)
    412         cbuffer = bevy.Read(chunk_size)
    413         if self.compression == lexicon.AFF4_IMAGE_COMPRESSION_ZLIB :
--> 414             return zlib.decompress(cbuffer)
    415 
    416         # Backwards compatibility with Scudette's AFF4 implementation.

error: Error -3 while decompressing data: incorrect header check

Full error output:
(MyEnv) user@kali:/tmp# rekall -f /mnt/Downloads/test.aff4

----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.7.1 (Hurricane Ridge).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------
[1] test.aff4 11:27:50> pslist
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in __getitem__(self, item)
   1173         try:
-> 1174             return super(DynamicNameSpace, self).__getitem__(item)
   1175         except KeyError:

KeyError: 'pslist'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/tmp/MyEnv/lib/python3.6/site-packages/rekall/addrspace.py in read_partial(self, addr, length)
    518         try:
--> 519             data = self._cache.Get(chunk_number)
    520         except KeyError:

/tmp/MyEnv/lib/python3.6/site-packages/rekall_lib/utils.py in NewFunction(self, *args, **kw)
    139         else:
--> 140             return f(self, *args, **kw)
    141 

/tmp/MyEnv/lib/python3.6/site-packages/rekall_lib/utils.py in Get(self, key)
    328             self.misses += 1
--> 329             raise KeyError(key)
    330 

KeyError: 0

During handling of the above exception, another exception occurred:

error                                     Traceback (most recent call last)
/tmp/MyEnv/lib/python3.6/site-packages/IPython/core/prefilter.py in prefilter_lines(self, lines, continue_prompt)
    333                              for lnum, line in enumerate(llines) ])
    334         else:
--> 335             out = self.prefilter_line(llines[0], continue_prompt)
    336 
    337         return out

/tmp/MyEnv/lib/python3.6/site-packages/IPython/core/prefilter.py in prefilter_line(self, line, continue_prompt)
    308             return normal_handler.handle(line_info)
    309 
--> 310         prefiltered = self.prefilter_line_info(line_info)
    311         # print "prefiltered line: %r" % prefiltered
    312         return prefiltered

/tmp/MyEnv/lib/python3.6/site-packages/IPython/core/prefilter.py in prefilter_line_info(self, line_info)
    250         """
    251         # print "prefilter_line_info: ", line_info
--> 252         handler = self.find_handler(line_info)
    253         return handler.handle(line_info)
    254 

/tmp/MyEnv/lib/python3.6/site-packages/IPython/core/prefilter.py in find_handler(self, line_info)
    257         for checker in self.checkers:
    258             if checker.enabled:
--> 259                 handler = checker.check(line_info)
    260                 if handler:
    261                     return handler

/tmp/MyEnv/lib/python3.6/site-packages/IPython/core/prefilter.py in check(self, line_info)
    413 
    414     def check(self, line_info):
--> 415         obj = self.shell.user_ns.get(line_info.ifun)
    416         if isinstance(obj, Macro):
    417             return self.prefilter_manager.get_handler_by_name('macro')

/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in get(self, item, default)
   1181     def get(self, item, default=None):
   1182         try:
-> 1183             return self[item]
   1184         except KeyError:
   1185             return default

/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in __getitem__(self, item)
   1174             return super(DynamicNameSpace, self).__getitem__(item)
   1175         except KeyError:
-> 1176             if getattr(self["session"].plugins, item):
   1177                 return self._prepare_runner(item)
   1178 

/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in __getattr__(self, name)
    153         pslist_plugin = plugins.pslist()
    154         """
--> 155         plugin_cls = self.GetPluginClass(name)
    156         if plugin_cls == None:
    157             return plugin_cls

/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in GetPluginClass(self, name)
    133         """
    134         # Try to see if the requested plugin is active right now.
--> 135         metadata = self.plugin_db.GetActivePlugin(name)
    136         if metadata == None:
    137             return metadata

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugin.py in GetActivePlugin(self, plugin_name)
    980         for command_metadata in self.db.get(plugin_name, []):
    981             plugin_cls = command_metadata.plugin_cls
--> 982             if plugin_cls.is_active(self.session):
    983                 results.append(command_metadata)
    984 

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugin.py in is_active(cls, session)
    438 
    439         else:
--> 440             return super(ProfileCommand, cls).is_active(session)
    441 
    442     def __init__(self, profile=None, **kwargs):

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugin.py in is_active(cls, session)
    225 
    226             if isinstance(mode, basestring):
--> 227                 if not session.GetParameter(mode):
    228                     return False
    229 

/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in GetParameter(self, item, default, cached)
    764         # can get if from a hook.
    765         try:
--> 766             result = self._RunParameterHook(item)
    767             if result is not None:
    768                 return result

/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in _RunParameterHook(self, name)
    799                     self._hook_locks.add(name)
    800                     hook = cls(session=self)
--> 801                     result = hook.calculate()
    802 
    803                     # Cache the output from the hook directly.

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/modes.py in calculate(self)
    113 
    114     def calculate(self):
--> 115         if self.session.profile:
    116             return self.session.GetParameter("live_mode") == "API"
    117 

/tmp/MyEnv/lib/python3.6/site-packages/rekall_lib/utils.py in __get__(self, *args, **kwargs)
   1077     def __get__(self, *args, **kwargs):
   1078         try:
-> 1079             return super(safe_property, self).__get__(*args, **kwargs)
   1080         except AttributeError as e:
   1081             message = "AttributeError raised: %s" % e

/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in profile(self)
   1058             return process_context
   1059 
-> 1060         res = self.GetParameter("profile_obj")
   1061         return res
   1062 

/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in GetParameter(self, item, default, cached)
    764         # can get if from a hook.
    765         try:
--> 766             result = self._RunParameterHook(item)
    767             if result is not None:
    768                 return result

/tmp/MyEnv/lib/python3.6/site-packages/rekall/session.py in _RunParameterHook(self, name)
    799                     self._hook_locks.add(name)
    800                     hook = cls(session=self)
--> 801                     result = hook.calculate()
    802 
    803                     # Cache the output from the hook directly.

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/guess_profile.py in calculate(self)
    728         if not self.session.physical_address_space:
    729             # Try to load the physical_address_space so we can scan it.
--> 730             if not self.session.plugins.load_as().GetPhysicalAddressSpace():
    731                 # If a filename was specified this should have worked, unless we
    732                 # could not open it.

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/core.py in GetPhysicalAddressSpace(self)
    376             # Try to get a physical address space.
    377             if self.pas_spec == "auto":
--> 378                 self.session.physical_address_space = self.GuessAddressSpace()
    379             else:
    380                 self.session.physical_address_space = self.AddressSpaceFactory(

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/core.py in GuessAddressSpace(self, base_as, **kwargs)
    475                 try:
    476                     base_as = cls(base=base_as, session=self.session,
--> 477                                   **kwargs)
    478                     self.session.logging.debug("Succeeded instantiating %s",
    479                                                base_as)

/tmp/MyEnv/lib/python3.6/site-packages/rekall_lib/registry.py in __call__(cls, *args, **kwargs)
     94 
     95     def __call__(cls, *args, **kwargs):
---> 96         res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
     97         res._object_id = UniqueObjectIdMetaclass.ID  # pylint: disable=protected-access
     98         UniqueObjectIdMetaclass.ID += 1

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/addrspaces/macho.py in __init__(self, **kwargs)
     34         super(MACHOCoreDump, self).__init__(**kwargs)
     35 
---> 36         self.check_file()
     37 
     38         # Try to parse the file now.

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/addrspaces/macho.py in check_file(self)
     57 
     58         # Must start with the magic for macho 64.
---> 59         self.as_assert((self.base.read(0, 4) == "\xcf\xfa\xed\xfe"),
     60                        "Header signature invalid")

/tmp/MyEnv/lib/python3.6/site-packages/rekall/addrspace.py in read(self, addr, length)
    486         result = b""
    487         while length > 0:
--> 488             data = self.read_partial(addr, length)
    489             if not data:
    490                 break

/tmp/MyEnv/lib/python3.6/site-packages/rekall/addrspace.py in read_partial(self, addr, length)
    521             # Just read the data from the real class.
    522             data = self.cached_read_partial(
--> 523                 chunk_number * self.CHUNK_SIZE, self.CHUNK_SIZE)
    524 
    525             self._cache.Put(chunk_number, data)

/tmp/MyEnv/lib/python3.6/site-packages/rekall/addrspace.py in cached_read_partial(self, addr, length)
    499         """Implement this to allow the caching mixin to cache these reads."""
    500         # By default call the next read_partial in the inheritance tree.
--> 501         return super(CachingAddressSpaceMixIn, self).read(addr, length)
    502 
    503     def read_partial(self, addr, length):

/tmp/MyEnv/lib/python3.6/site-packages/rekall/addrspace.py in read(self, addr, length)
    587 
    588         while length > 0:
--> 589             buf = self._read_chunk(addr, length)
    590             if not buf:
    591                 break

/tmp/MyEnv/lib/python3.6/site-packages/rekall/addrspace.py in _read_chunk(self, addr, length)
    664         file_offset = run.file_offset + addr - start
    665 
--> 666         return run.address_space.read(file_offset, available_length)
    667 
    668     def _write_chunk(self, addr, buf):

/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/addrspaces/aff4.py in read(self, offset, length)
     67     def read(self, offset, length):
     68         self.stream.seek(offset)
---> 69         return self.stream.read(length)
     70 
     71     def end(self):

/tmp/MyEnv/lib/python3.6/site-packages/pyaff4/aff4.py in read(self, length)
    264 
    265     def read(self, length=1024*1024):
--> 266         return self.Read(length)
    267 
    268     def seek(self, offset, whence=0):

/tmp/MyEnv/lib/python3.6/site-packages/pyaff4/aff4_map.py in Read(self, length)
    249                         range.target_offset_at_map_offset(self.readptr))
    250 
--> 251                     buffer = target_stream.Read(length_to_read_in_target)
    252                     assert len(buffer) == length_to_read_in_target
    253                     result += buffer

/tmp/MyEnv/lib/python3.6/site-packages/pyaff4/aff4_image.py in Read(self, length)
    291 
    292         while chunks_to_read > 0:
--> 293             chunks_read, data = self._ReadPartial(chunk_id, chunks_to_read)
    294             if chunks_read == 0:
    295                 break

/tmp/MyEnv/lib/python3.6/site-packages/pyaff4/aff4_image.py in _ReadPartial(self, chunk_id, chunks_to_read)
    377 
    378                     # Read a full chunk from the bevy.
--> 379                     data = self._ReadChunkFromBevy(chunk_id, bevy)
    380                     self.cache[chunk_id] = data
    381 

/tmp/MyEnv/lib/python3.6/site-packages/pyaff4/aff4_image.py in _ReadChunkFromBevy(self, chunk_id, bevy)
    412         cbuffer = bevy.Read(chunk_size)
    413         if self.compression == lexicon.AFF4_IMAGE_COMPRESSION_ZLIB :
--> 414             return zlib.decompress(cbuffer)
    415 
    416         # Backwards compatibility with Scudette's AFF4 implementation.

error: Error -3 while decompressing data: incorrect header check

[5]+  Stopped                 rekall -f /mnt/Downloads/test.aff4

**Comment by scudette** [comment]
This seems to be a bug with the python aff4 library. We have changed it to support the new AFF4 standard with a backwards compatibility layer and it appears that it does not properly detect the old version.

This should be fixed with https://github.com/google/aff4/commit/62af173c4d26139227bb64e6988ef2899bee5f16

Thanks for reporting!

**Comment by dougkite** [comment]
How do I install from the commit? I tried:
pip install git+https://github.com/google/aff4@62af173c4d26139227bb64e6988ef2899bee5f16

I get the message there is no setup.py

Thanks for the quick reply. Sorry I am new to installing from repo

Collecting git+https://github.com/google/aff4@62af173c4d26139227bb64e6988ef2899bee5f16
  Cloning https://github.com/google/aff4 (to 62af173c4d26139227bb64e6988ef2899bee5f16) to /tmp/pip-jmuq2v9u-build
  Could not find a tag or branch '62af173c4d26139227bb64e6988ef2899bee5f16', assuming commit.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/MyEnv/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-jmuq2v9u-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-jmuq2v9u-build/

**Comment by scudette** [comment]
Ah sorry you just clone the repo first then simply install the code from it:

```
git clone https://github.com/google/aff4.git
pip install -e aff4/pyaff4/
```

Installing it with the command you used would work except that the setup.py is not in the top level directory and this confuses pip.

Note that I have no incremented the version yet (I will do so in the next release) so you need to force install (or use the --editable flag) to make sure it picks the latest.

**Comment by dougkite** [comment]
That solved the installation problem, and it was then able to open the image with snappy compression.

However, not many of the plugins work. pslist works, but not many others: netscan, psscan, psxview (have tested images with both snappy and zlib compression)

imageinfo says the version is:
NT Build             15063.rs2_release.170317-1834

should most plugins work on this version? is this a structure change problem?

Thanks

**Comment by scudette** [comment]
Yeah it looks like this is an up to date windows 10 machine. I think psscan should work. Probably the network plugins are not going to work (because they are mostly undocumented structures). Psxview should work with git head. 

Please file issues if a plugin should work but does not.

**Comment by dougkite** [comment]
Will do. Thanks.

Issue was resolved by commit to google/aff4.
