### ISSUE TITLE
Rekall docker 1.6 . The artifacts_collector didn't find history (firefox, google). It's work ?

### ISSUE THREAD

**Issue by winnotor** [google/rekall#351]
HI, all is in the issue title.

There isn't error, but not matches. I'm sure there's history about the navigation.

strings -af memory.raw | grep -i firefox  ===> matches
strings -af memory.raw | grep -i google-chrome ===> matches

command on the memory .

**Comment by scudette** [comment]
Im not sure what you are saying here. Can you please share the memory image? (you can share privately by sending the link to support@rekall-forensics.com)

What plugin are you running? What do you expect to see? Any debugging output?

**Comment by winnotor** [comment]
alias rekall='docker run -it --rm -v $(pwd):/data:rw blacktop/rekall:1.6 $@

On a linux memory acquisition 

---------
rekall -f memory.raw  -p profile_volatility-4.4.0-53-generic.zip.json
---------

![image](https://user-images.githubusercontent.com/22667983/35109786-a3090c94-fc77-11e7-99ff-7c270c9df9e7.png)

**Comment by scudette** [comment]
Ah i see what you mean now. Sorry I was missing critical context :-). 

The artifact collector collects the artifacts from the forensic artifacts project (https://github.com/ForensicArtifacts/)

As you can see the artifact you are trying to collect are FILE based artifacts (https://github.com/ForensicArtifacts/artifacts/blob/3efd542df75ca721531baeceea2916fa0a49840e/data/webbrowser.yaml#L103) which means they essentially run glob on the filesystem. They work when Rekall is running in --live API mode on the actual system (essentially they translate to running the glob() plugin).

So you would need to run `rekall --live API `  inside the system you want to investigate in live mode.

Hope this clarifies this feature.

**Comment by winnotor** [comment]
Hi, thank's for your response, 
but I try it

rekall  --live API  -p profile_volatility-4.4.0-53-generic.zip.json

![image](https://user-images.githubusercontent.com/22667983/35125594-7e3208de-fcaa-11e7-8226-33083bf446e5.png)



 there seems to be the same issue

**Comment by scudette** [comment]
Forensic artifacts are about collecting files - they are not about parsing those files out. So Rekall will just execute the glob expressions in the artifact definition.

By default it just lists the files it found, but if you also specify an output path and a writer and tell it to copy the files themselves, it will collect these files:

```
[1] Live (API) 22:28:11> artifact_collector "BrowserHistory", writer="Zip", output_path="/tmp/output.zip", copy_files=True
-----------------------> artifact_collector("BrowserHistory", writer="Zip", output_path="/tmp/output.zip", copy_files=True)
------------------------  
Artifact: BrowserHistory  
------------------------  
-----------------------  
Artifact: ChromeHistory  
-----------------------  
  st_mode    st_nlink st_uid     st_gid     st_size st_mtime           filename                                       
  -------    -------- ------     ------     ------- --------           --------                                       
  -rw-r--r-- 1        mic (1000) mic (1000) 557056  1514136849.5402062 /home/mic/.config/google-chrome/Default/History
------------------------  
Artifact: FirefoxHistory  
------------------------  
  st_mode    st_nlink st_uid     st_gid     st_size  st_mtime          filename                                                 
  -------    -------- ------     ------     -------  --------          --------                                                 
  -rw-r--r-- 1        mic (1000) mic (1000) 10485760 1506396719.343707 /home/mic/.mozilla/firefox/d1q55xx6.default/places.sqlite
----------------------  
Artifact: OperaHistory  
----------------------  
Out<22:28:11> Plugin: artifact_collector (ArtifactsCollector)
[1] Live (API) 22:28:13> !unzip -l /tmp/output.zip
Archive:  /tmp/output.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   557056  2017-12-24 09:34   home/mic/.config/google-chrome/Default/History
      569  2018-01-28 22:28   artifacts/ChromeHistory.json
      168  2018-01-28 22:28   artifacts/ChromeHistory.csv
 10485760  2017-09-25 20:31   home/mic/.mozilla/firefox/d1q55xx6.default/places.sqlite
      581  2018-01-28 22:28   artifacts/FirefoxHistory.json
      179  2018-01-28 22:28   artifacts/FirefoxHistory.csv
      366  2018-01-28 22:28   artifacts/OperaHistory.json
       58  2018-01-28 22:28   artifacts/OperaHistory.csv
---------                     -------
 11044737                     8 files
```
