### ISSUE TITLE
pmem.h:92:20: error: ‘TCLAP::MultiArgToNextFlag’ is not a template

### ISSUE THREAD

**Issue by grassy** [google/rekall#390]
I am trying to build pmem static libraries on Ubuntu17.10,  but the bellow error occurs where i build linpmem:

In file included from /home/meimei/static//include/aff4/aff4_imager_utils.h:23:0,
                 from pmem.h:23,
                 from pmem_imager.cc:16:
/home/meimei/static//include/aff4/config.h:101:0: note: this is the location of the previous definition
 #define PACKAGE_VERSION "1.0"
 
In file included from linux_pmem.h:19:0,
                 from linux_pmem.cc:16:
pmem.h: In member function ‘virtual aff4::AFF4Status aff4::PmemImager::RegisterArgs()’:
pmem.h:92:20: error: ‘TCLAP::MultiArgToNextFlag’ is not a template
         AddArg(new TCLAP::MultiArgToNextFlag<std::string>(
                    ^~~~~
In file included from pmem_imager.cc:16:0:
pmem.h: In member function ‘virtual aff4::AFF4Status aff4::PmemImager::RegisterArgs()’:
pmem.h:92:20: error: ‘TCLAP::MultiArgToNextFlag’ is not a template
         AddArg(new TCLAP::MultiArgToNextFlag<std::string>(
                    ^~~~~
pmem_imager.cc: In member function ‘virtual aff4::AFF4Status aff4::PmemImager::handle_pagefiles()’:
pmem_imager.cc:94:24: error: ‘TCLAP::MultiArgToNextFlag’ is not a template
     pagefiles = GetArg<TCLAP::MultiArgToNextFlag<std::string>>(
                        ^~~~~
Makefile:545: recipe for target 'linpmem-linux_pmem.o' failed
make: *** [linpmem-linux_pmem.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:531: recipe for target 'linpmem-pmem_imager.o' failed
make: *** [linpmem-pmem_imager.o] Error 1

**Comment by scudette** [comment]
Linpmem moved to its new home as part of the c-aff4 project:

https://github.com/Velocidex/c-aff4

We should remove it from Rekall's tree.  If you still have issues building please file an issue.

**Comment by grassy** [comment]
Thank you very much.
