### ISSUE TITLE
Rekall profile: no $STRUCTS section found

### ISSUE THREAD

**Issue by Skakf** [google/rekall#393]
Hello, I think I meet a problem with rekall. 

I installed a Win7_VM on Ubuntu 16.04,Xen4.9

when I used "vmi-win-guid",libvmi works well, while when I tried to operate "vmi-process-list win7"

the result is :

> **The running Xen version is 4.9
--found Xen
LibVMI Version 0.11.0
LibVMI Driver Mode 0
**The running Xen version is 4.9
--completed driver init.
--got id from name (win7 --> 4)
**set image_type = win7
**set vm_type HVM
--xen: setup live mode
**set allocated_ram_size = 8004b000, max_physical_address = 0xff001000
**set pae = 1
**set pse = 1
**set lme = 1
**IA-32e paging
**sanity checking cr3 = 0x0000000000187000
--looking for config file at /home/ubuntu/Desktop/Drakvuf/drakvuf/libvmi/examples/libvmi.conf
--looking for config file at /home/ubuntu/etc/libvmi.conf
--looking for config file at /home/ubuntu/etc/libvmi.conf
--looking for config file at /etc/libvmi.conf
**Using config file at /etc/libvmi.conf
**set os_type to Windows.
Rekall profile: no $STRUCTS section found
Failed to init LibVMI library.

The core-issue is that "**Rekall profile: no $STRUCTS section found**"

The pdb I'm using is the file ntkrnlmp.pdb, and the PDB GUID:f8e2a8b5c9b74bf4a6e4a48f180099942

My rekall version: 

> This is Rekall Version 1.7.1 (Hurricane Ridge)
> {'pep440': u'1.7.1', u'rc': u'0', u'version': u'1.7.1', 'error': 'Not in a git repository.', u'codename': u'Hurricane Ridge', u'post': u'0'}

I tried the following steps:
	

> rekall -v  fetch_pdb ntkrnlmp f8e2a8b5c9b74bf4a6e4a48f180099942
> 	rekal -v parse_pdb ntkrnlmp > /tmp/win7.rekall.json
> 

However, the win7.rekall.json doesn't contain the proper $STRUCTS
The $METADATA is :
	
> $METADATA": {
>   	"GUID_AGE": "-5",
>  	 "PDBFile": "ntkrnlmp",
>   	"ProfileClass": "Ntkrnlmp",
>  	 "Timestamp": "2009-07-13 23:40:54Z",
>  	 "Type": "Profile",
>  	 "Version": 20000404
>  	},

I have seen from another issue that maybe there is somgthing wrong with my GUID_AGE? 
But I don't know what should I do now.

My python version is python 2.7.12. Should I change it to python3 or another rekall version?

Please help me, Thank you very much!

**Comment by scudette** [comment]
It is quite common for the MS symbol server to serve broken PDB files. Sometimes MS fix their published PDB files by pushing a new version but this one seems to be from 2009 so I wouldnt hold my breath.

It is possible to fix the JSON file by simply copying the $STRUCT section from another PDB file into this JSON file. This generally works but you need the same windows version, architecture etc. We do not have an automated way to do this yet though. You can either write a quick script or just vi or emacs to do it manually. Try to clone the profile repository and use zgrep to extract the Timestamp of all the files to find something around the same release time.

**Comment by Skakf** [comment]
Yeah!  I don't know whether the rekall version is related to python version.  But after I change to python3.5, and do the same operation, it works! 
The new pdb file contains the $STRUCTS and my libvmi runs vmi-process-list succeed!

Thank you all the same :) !
