### ISSUE TITLE
error: unrecognized arguments.    Webconcle cannot start

### ISSUE THREAD

**Issue by AlexsanderShaw** [google/rekall#397]
Hello,
Please help me .I get an error while trying to start up the webconsole.I have installed rekall and rekall-gui following the instructions for linux, and then i installed the workshop follwed wtih [https://github.com/scudette/memory-analysis](url) ,but when  I try to start the webconsole followed with README, I get the "unrecognized command" error, as you can see below:

`(MyEnv) root@ubuntu:~/memory-analysis# rekal -v webconcle --broewser source/02-What_is_memory/
`
`2018-04-28 13:02:10,240:DEBUG:rekall.1:Logging level set to 10
usage: rekall [-p PROFILE] [-v] [-q] [--debug] [--output_style {concise,full}]
              [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
              [--log_domain [{PageTranslation} [{PageTranslation} ...]]]
              [--pager PAGER] [--paging_limit PAGING_LIMIT]
              [--colors {auto,yes,no}] [-F FORMAT]
              [--plugin [PLUGIN [PLUGIN ...]]] [-h] [--cache CACHE]
              [--repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]]
              [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT]
              [--max_collector_cost MAX_COLLECTOR_COST] [--home HOME]
              [--logging_format LOGGING_FORMAT]
              [--performance {normal,fast,thorough}] [--live LIVE]
              [--cpu_quota CPU_QUOTA] [--load_quota LOAD_QUOTA]
              [--agent_configuration AGENT_CONFIGURATION] [--dtb DTB]
              [-o FILE_OFFSET] [--ept EPT [EPT ...]] [--timezone TIMEZONE]
              [--cache_dir CACHE_DIR]
              [--highlighting_style {manni,igor,lovelace,xcode,vim,autumn,abap,vs,rrt,native,perldoc,borland,arduino,tango,emacs,friendly,monokai,paraiso-dark,colorful,murphy,bw,pastie,rainbow_dash,algol_nu,paraiso-light,trac,default,algol,fruity}]
              [--name_resolution_strategies [{Module,Symbol,Export} [{Module,Symbol,Export} ...]]]
              [--autodetect_build_local_tracked [AUTODETECT_BUILD_LOCAL_TRACKED [AUTODETECT_BUILD_LOCAL_TRACKED ...]]]
              [--pagefile [PAGEFILE [PAGEFILE ...]]]
              [--autodetect {linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux} [{linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux} ...]]
              [--autodetect_threshold AUTODETECT_THRESHOLD]
              [--autodetect_build_local {full,basic,none}]
              [--autodetect_scan_length AUTODETECT_SCAN_LENGTH] [--version]
              [-]
rekall: error: unrecognized arguments: webconcle --broewser source/02-What_is_memory/
`

(MyEnv) root@ubuntu:~/rekall# ls
AUTHORS.md   LEGAL.txt    rekall-agent     requirements.txt  _version.py
config       LICENSE.txt  rekall-core      resources         version.py
contrib      MANIFEST.in  rekall.egg-info  setup.py          _version.pyc
CREDITS.txt  osx          rekall-gui       src               version.yaml
debian       README.md    rekall-lib       tools

Please help me .I want to learn rekall,but i dont know how to solve it.
Thanks very much.

**Comment by scudette** [comment]
I think you mis-spelt webconsole above. The webconsole is not really supported any more and has been deprecated. It might still work but we do not guarantee.
