### ISSUE TITLE
aff4 extract

### ISSUE THREAD

**Issue by jeffg2k** [google/rekall#400]
I'm trying to extract the PhysicalMemory stream out of a aff4 file using osxpmem.  But when I run the various commands I see online, I get the message:
> 2018-05-09 22:14:44 E Can not specify an export and an output volume at the same time (did you mean --export_dir).
> 2018-05-09 22:14:44 E Imaging failed with error: -5

Various commands I've tried..
```
./osxpmem.app/osxpmem memory.aff4 --export PhysicalMemory -o memory.img
./osxpmem.app/osxpmem --export /PhysicalMemory --output memory.img memory.aff4
./osxpmem.app/osxpmem --export /PhysicalMemory --output_dir ./tmp memory.aff4
```
What is the correct command or is something broken?

**Comment by jeffg2k** [comment]
This produced something, but unable to read it in my other memory tools.
`./rekal -f ../memory.aff4 imagecopy --output-image=./tmp/memory.img`

**Comment by scudette** [comment]
AFF4 volumes can have multiple streams so you need to specify which one you want to export.  For example using https://github.com/Velocidex/c-aff4/releases ::
```
./linpmem_3.0rc2.bin -D . -e '*' test.aff4  -dd
```

Will just extract all streams to the current directory.  A directory structure will be created with the UUID at the top level.

**Comment by jeffg2k** [comment]
Appreciate the assist.  That command didn't seem to produce anything for me though.  No directory or files were created.
```
2018-05-10 07:12:24 I Preloading AFF4 Volume: file:///memory.aff4
2018-05-10 07:12:24 I Loaded AFF4 volume URN aff4://efa48b0d-0a80-4e88-96ba-4d2bfa2b0cfa from zip file.
2018-05-10 07:12:24 I Global offset: -3c
```

**Comment by scudette** [comment]
Can you paste the output with -l ?  Its weird that the Global offset is negative. Can you please paste the output of unzip -l, unzip -t or python -m zipfile -t XX.aff4?

How did you acquire the image? How large is it?

**Comment by jeffg2k** [comment]
In my tests, I must have done something to the file as the md5 didn't match the original.  So I restored it and got this:
```
2018-05-10 09:00:44 I Preloading AFF4 Volume: file:///Users/Jeff/Desktop/NetWars/work/malware_analysis/Post_Malware.raw
2018-05-10 09:00:44 I Loaded AFF4 volume URN aff4://efa48b0d-0a80-4e88-96ba-4d2bfa2b0cfa from zip file.
2018-05-10 09:00:44 I Global offset: 0
```
Running unzip -l and unzip -t were successful. 
`543967949                     352 files`

**Comment by jeffg2k** [comment]
I reran this command after restoring the file and it worked.
`./rekal -f ../memory.aff4 imagecopy --output-image=./tmp/memory.img`

**Comment by scudette** [comment]
Try to extract with the most recent release (osxpmem 3.2) https://github.com/Velocidex/c-aff4/releases/tag/3.2

**Comment by jeffg2k** [comment]
I'll have to see if I still have it.  I don't expect I do though.
