### ISSUE TITLE
ldrmodules and malfind

### ISSUE THREAD

**Issue by granule** [google/rekall#42]
fresh install - no updates to OS
Ubuntu 14.04

wget SIFT workstation

python ver:  2.7.6 (default)

rekall ver:  Col de la Croix (1.2.0)

suspected RAM image: Win7 SP1
cmd: rekal -f <RAM.img> ldrmodules | tee ldrmodules.txt
...and...
rekal -f <RAM.img> malfind | tee malfind.txt

ran both plugins without the pipe and tee and get the same output

ldrmodules gets cranking and then starts with errors
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 602, in _RunPlugin
    plugin_obj.render(ui_renderer)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/windows/malware/malfind.py", line 190, in render
    for vad, name in self.list_mapped_files(task))
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/windows/malware/malfind.py", line 189, in <genexpr>
    mapped_files = dict((vad.Start, name)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/windows/malware/malfind.py", line 157, in list_mapped_files
    for vad in task.RealVadRoot.traverse():
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/overlays/windows/common.py", line 1233, in traverse

and then mostly 'line 1233' and 'line 1229' errors until at bottom:
RuntimeError: Vad tree too deep - something went wrong!

under malfind it barely started before most of the same output and same finishing error

tried the debug flag with malfind and get:
> /usr/local/lib/python2.7/dist-packages/rekall/plugins/overlays/windows/common.py(1210)traverse()
-> raise RuntimeError("Vad tree too deep - something went wrong!")
(Pdb)

**Comment by granule** [comment]
OK, now I tried to run malfind on a specific process.  First I used psxview and found the first process that has five false's , a true and one more false as ouput.  I ran the following commands:
rekal -f <image file name> --pid XXXX
rekal -f <image file name> pid=XXXX
rekal -f <image file name> --pid=XXXX
rekal -f <image file name> pid XXXX
...all provide no output...
btw - using hma while running the process - does that affect any output functions?

**Comment by scudette** [comment]
This looks very strange to me. The discrepancy between the different process listing methods is very concerning and indicates a serious amount of smear on this image. How much ram was there in that machine? did the imaging take exceptionally long?

I recent versions of Rekall we tried to make the vad traversal more robust so it will just skip too deep vad trees and try to complete the analysis anyway. Maybe its worth a shot with 1.3.1?

Thanks

**Comment by granule** [comment]
The machine had 8GB of ram.  Unfortunately, I was not the one to conduct
the imaging and the images were sent to me.  The initial send was via a
network connection and took a bit to complete.  However, the hash values
matched upon completion of the transfer.  I also received a HD with all
image files via mail and the same hash values were reported and verified.
It was a while ago but I believe I also converted them from E01 to dd and
ran them through Rekall both ways.
I would have liked to try the newest version  of Rekall but I no longer
have access to the data.

Thanks again for getting back to me!
