### ISSUE TITLE
Weak Encryption：Insecure Mode of Operation

### ISSUE THREAD

**Issue by 360CodeSafe** [google/rekall#494]
rekall-master/rekall-core/rekall/plugins/windows/registry/hashdump.py 205
![image](https://user-images.githubusercontent.com/39950310/56636127-6232bd80-669a-11e9-9926-c782d89fd59d.png)
rekall-master/rekall-core/rekall/plugins/windows/registry/hashdump.py 176
![image](https://user-images.githubusercontent.com/39950310/56636154-7aa2d800-669a-11e9-8dec-23f1b53f3174.png)
the problem with ECB mode is that encrypting the same blockof plaintext using ECB mode always yields the same block of ciphertext.
CBC mode is the superior choice as it does not have this weakness.

**Comment by scudette** [comment]
Perhaps you should provide this feedback to Microsoft? This code simply emulates the windows hashing functions (for very old versions admittedly).
