### ISSUE TITLE
PSLIST Plugin Not available

### ISSUE THREAD

**Issue by l0gm0nk3y** [google/rekall#53]
Just dowloaded and installed Rekall_1.2.1_Col.de.la.Croix_x64_signed.exe, however, I get the following when I run the following commands:

winpmem_1.6.2.exe -l

rekal.exe -f \\.\pmem -v pslist

.... 
ERROR:root:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "<string>", line 81, in <module>
  File "<string>", line 54, in main
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.args
", line 404, in parse_args
rekall.plugin.PluginError: Plugin pslist is not available for this configurationles match this image. Try specifying manually.Traceback (most recent call last):File "<string>", line 81, in <module>File "<string>", line 54, in mainFile "C:\cygwin\home\mic\projects\rekall\build\rekal\

**Comment by parkisan** [comment]
Could you please provide the full -v output?

You could also see if specifying -f \\.\pmem helps. Note the double backslash in pmem.

**Comment by l0gm0nk3y** [comment]
Thanks for responding so quickly.  
C:\Program Files\Rekall>rekal.exe -f \\.\pmem -v pslist
DEBUG:root:Voting round with base: None
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:root:Failed instantiating VMSSAddressSpace: No base address space provided

DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:root:Failed instantiating MACHOCoreDump: Must stack on another address spa
ce
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:root:Failed instantiating VMemAddressSpace: No base address space provided

DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:root:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
DEBUG:root:Failed instantiating VTxPagedMemory: No base Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:root:Failed instantiating WindowsCrashBMP: Must stack on another address s
pace
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>

DEBUG:root:Failed instantiating KCoreAddressSpace: Must stack on another address
 space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace3
2'>
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: No base address space p
rovided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace6
4'>
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: No base address space p
rovided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:root:Failed instantiating Elf64CoreDump: Must stack on another address spa
ce
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'
>
DEBUG:root:Succeeded instantiating Win32FileAddressSpace
DEBUG:root:Voting round with base: Win32FileAddressSpace
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:root:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:root:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:root:Failed instantiating VMemAddressSpace: Only VMEM files supported.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:root:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
DEBUG:root:Failed instantiating VTxPagedMemory: No EPT specified
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:root:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>

DEBUG:root:Failed instantiating KCoreAddressSpace: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace3
2'>
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace6
4'>
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: Header signature invali
d
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:root:Failed instantiating Elf64CoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'
>
DEBUG:root:Failed instantiating Win32FileAddressSpace: Must be first Address Spa
ce
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
DEBUG:root:Failed instantiating FileAddressSpace: Must be first Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileA
ddressSpace'>
DEBUG:root:Failed instantiating MmapFileAddressSpace: Must be first Address Spac
e
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddress
Space'>
DEBUG:root:Failed instantiating GlobalOffsetAddressSpace: File offset not specif
ied.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAdd
ressSpace'>
DEBUG:root:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not speci
fied
INFO:root:Autodetected physical address space Win32FileAddressSpace
DEBUG:root:Will detect profile using these Detectors: nt_index,osx,pe,rsds,ntfs,
linux
DEBUG:root:Opened url https://raw.githubusercontent.com/google/rekall-profiles/m
aster/v1.0/inventory
DEBUG:root:Skipped profile nt/eprocess_index from https://raw.githubusercontent.
com/google/rekall-profiles/master/v1.0 (Not in inventory)
DEBUG:root:Opened url http://profiles.rekall-forensic.com/v1.0/inventory
DEBUG:root:Skipped profile nt/eprocess_index from http://profiles.rekall-forensi
c.com/v1.0 (Not in inventory)
DEBUG:root:Skipped profile nt/index from https://raw.githubusercontent.com/googl
e/rekall-profiles/master/v1.0 (Not in inventory)
DEBUG:root:Skipped profile nt/index from http://profiles.rekall-forensic.com/v1.
0 (Not in inventory)
DEBUG:root:Skipped profile OSX/index from https://raw.githubusercontent.com/goog
le/rekall-profiles/master/v1.0 (Not in inventory)
DEBUG:root:Skipped profile OSX/index from http://profiles.rekall-forensic.com/v1
.0 (Not in inventory)
DEBUG:root:Skipped profile pe from https://raw.githubusercontent.com/google/reka
ll-profiles/master/v1.0 (Not in inventory)
DEBUG:root:Skipped profile pe from http://profiles.rekall-forensic.com/v1.0 (Not
 in inventory)
DEBUG:root:Skipped profile ntfs from https://raw.githubusercontent.com/google/re
kall-profiles/master/v1.0 (Not in inventory)
DEBUG:root:Skipped profile ntfs from http://profiles.rekall-forensic.com/v1.0 (N
ot in inventory)
ERROR:root:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "<string>", line 81, in <module>
  File "<string>", line 54, in main
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.args
", line 404, in parse_args
rekall.plugin.PluginError: Plugin pslist is not available for this configuration

**Comment by parkisan** [comment]
Could you run and paste the output of:


rekal -f \\.\pmem version_scan --name_regex "^nt"


This is to see which GUIDs Rekall finds for the Windows kernel of this
image.

**Comment by l0gm0nk3y** [comment]
c:\Program Files\Rekall>rekal -f \\.\pmem version_scan --name_regex "^nt"
ERROR:root:No profiles match this image. Try specifying manually.
  Offset (P)             GUID/Version                         PDB
-------------- --------------------------------- ------------------------------

c:\Program Files\Rekall>

**Comment by parkisan** [comment]
Actually, does this machine have good connectivity? I think there may be some issues there. Like the inventory you're getting back being garbage.

Can you "wget https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz" or equivalent, to see what you're getting back from within that VM?

**Comment by l0gm0nk3y** [comment]
I am behind a proxy that requires authentication.  Can I install inventory locally?

**Comment by scudette** [comment]
Ah that explains it. Sure you can just do:

git clone https://github.com/google/rekall-profiles

Then edit the path in ~/.rekallrc:

profile_path:
 - /home/scudette/projects/rekall-profiles/

Thanks
Micael

**Comment by l0gm0nk3y** [comment]
Thanks.  But how would you do that when you have pulled back a remote shell onto a target machine that does not have rekall installed?  Can you pass in profile_path value at the CLI or set it as in ENV variable?

**Comment by parkisan** [comment]
Michael showed how to download the full profile repository so that you can have Rekall reference it via a local path instead of requiring the box with Rekall have Internet access. Once you've somehow replicated the profile repo on the box you'll be running Rekall in, this should work:

rekal -f image --profile_path "PATH 1" "PATH 2" - pslist -v

Note the "-" after the list of profile paths. i.e:

rekal -f \\\\.\pmem --profile_path "C:\my-profile-repo" - pslist -v

**Comment by l0gm0nk3y** [comment]
Thanks again for all your help!  I am now getting  the following:

c:\Program Files\Rekall>rekal.exe -f \\.\pmem --profile_path "c:\Program Files\R
ekall\rekall-profiles-gh-pages" - -v pslist
....              
....
DEBUG:root:Will detect profile using these Detectors: nt_index,osx,pe,rsds,ntfs,
linux
INFO:root:Loaded profile nt/eprocess_index from Directory:z:\Dev\rekall-profiles
-gh-pages\v1.0
INFO:root:Loaded profile nt/index from Directory:z:\Dev\rekall-profiles-gh-pages
\v1.0
INFO:root:Loaded profile OSX/index from Directory:z:\Dev\rekall-profiles-gh-page
s\v1.0
INFO:root:Loaded profile pe from Directory:z:\Dev\rekall-profiles-gh-pages\v1.0
INFO:root:Loaded profile ntfs from Directory:z:\Dev\rekall-profiles-gh-pages\v1.
0
DEBUG:root:Skipped profile nt/GUID/A3AD9FD2EFE44888BEE20BC56BFD77CE2 from z:\Dev
\rekall-profiles-gh-pages/v1.0 (Not in inventory)
DEBUG:root:Skipped profile nt/GUID/326B00DFCD674C7E9A1F192D3A9DE1302 from z:\Dev
\rekall-profiles-gh-pages/v1.0 (Not in inventory)
DEBUG:root:Skipped profile nt/GUID/76280CA49D9549AD9030AAB3B2BB97B32 from z:\Dev
\rekall-profiles-gh-pages/v1.0 (Not in inventory)
DEBUG:root:Skipped profile nt/GUID/3ECCF4080DDC42918CCB81353F97751E2 from z:\Dev
\rekall-profiles-gh-pages/v1.0 (Not in inventory)
INFO:root:Loaded profile nt/GUID/FFFBFF4681DA4D1CA9AC045FFF5451C32 from Director
y:z:\Dev\rekall-profiles-gh-pages\v1.0
INFO:root:Detected ntkrnlmp.pdb with GUID FFFBFF4681DA4D1CA9AC045FFF5451C32
DEBUG:root:Detection method rsds worked at offset 0x6f4681c
_EPROCESS          Name          PID   PPID   Thds    Hnds    Sess  Wow64
    Start                     Exit
---------- -------------------- ----- ------ ------ -------- ------ ------ -----
------------------- ------------------------
DEBUG:root:Listed 0 processes using PsActiveProcessHead
DEBUG:root:Listed 0 processes using PsActiveProcessHead
DEBUG:root:Listed 0 processes using CSRSS
DEBUG:root:Listed 0 processes using PspCidTable
DEBUG:root:Listed 0 processes using PsActiveProcessHead
DEBUG:root:Listed 0 processes using CSRSS
DEBUG:root:Listed 0 processes using PspCidTable
DEBUG:root:Listed 0 processes using Sessions
DEBUG:root:Listed 0 processes using Handles
DEBUG:root:Listed 0 processes using Sessions
DEBUG:root:Listed 0 processes using Handles

**Comment by l0gm0nk3y** [comment]
Any update on this?  Is this a user error or is something with a profile mismatch?

**Comment by parkisan** [comment]
This seems to be opening your profile from z:\Dev\rekall-profiles-gh-pages\, but you specified "c:\Program Files\Rekall\rekall-profiles-gh-pages" in the command line.

Is "c:\Program Files\Rekall\"  a junction point to "Z:\Dev" ?
Or does your .rekallrc file have this directory in the path?

Is "z:\Dev\rekall-profiles-gh-pages\" properly up to date?


Have you tried with the latest release? Note that in the new release it's not --profile_path but --repository_path.

**Comment by l0gm0nk3y** [comment]
I am running Rekall_1.2.1_Col.de.la.Croix_x64_signed from remote share and I do not see --repository_path as an option.  In addition, I have downloaded the rekall-profiles-gh-pages package which I am pointing at.  See above.  Is there an update to this profile package?

My steps are:
1) remote onto target using psexec
    psexec \\<remote_target> cmd.exe

2) map share where compiled Rekall is stored
    net use T: \\shareHost\shareDir /user:<user> <password>

3)CD into share
  T:
  cd T:\Dev\Rekall

4)Load winpmem
    .\winpmem_1.6.2.exe -l

5)Run rekall
  T:\Dev\Rekall>rekal.exe -f \\.\pmem --profile_path t:\Dev\rekall-profiles-gh-pag
es - -v pslist
...
DEBUG:root:Will detect profile using these Detectors: nt_index,osx,pe,rsds,ntfs,
linux
INFO:root:Loaded profile nt/eprocess_index from Directory:t:\Dev\rekall-profiles
-gh-pages\v1.0
INFO:root:Loaded profile nt/index from Directory:t:\Dev\rekall-profiles-gh-pages
\v1.0
INFO:root:Loaded profile OSX/index from Directory:t:\Dev\rekall-profiles-gh-page
s\v1.0
INFO:root:Loaded profile pe from Directory:t:\Dev\rekall-profiles-gh-pages\v1.0
INFO:root:Loaded profile ntfs from Directory:t:\Dev\rekall-profiles-gh-pages\v1.
0
DEBUG:root:Skipped profile nt/GUID/76280CA49D9549AD9030AAB3B2BB97B32 from t:\Dev
\rekall-profiles-gh-pages/v1.0 (Not in inventory)
DEBUG:root:Skipped profile nt/GUID/553423E8A3BD40A4AE66CD040CBB54DF2 from t:\Dev
\rekall-profiles-gh-pages/v1.0 (Not in inventory)
DEBUG:root:Skipped profile nt/GUID/8C2B2BA404E547A6BC42D6036FF054242 from t:\Dev
\rekall-profiles-gh-pages/v1.0 (Not in inventory)
DEBUG:root:Skipped profile nt/GUID/EBC566F91DFB4E18A8A0703D63E6A3E32 from t:\Dev
\rekall-profiles-gh-pages/v1.0 (Not in inventory)
INFO:root:Loaded profile nt/GUID/00625D7D36754CBEBA4533BA9A0F3FE22 from Director
y:t:\Dev\rekall-profiles-gh-pages\v1.0
INFO:root:Detected ntkrnlmp.pdb with GUID 00625D7D36754CBEBA4533BA9A0F3FE22
DEBUG:root:Detection method rsds worked at offset 0x2543559c
_EPROCESS          Name          PID   PPID   Thds    Hnds    Sess  Wow64
    Start                     Exit
---------- -------------------- ----- ------ ------ -------- ------ ------ -----
------------------- ------------------------
DEBUG:root:Listed 0 processes using PsActiveProcessHead
DEBUG:root:Listed 0 processes using PsActiveProcessHead
DEBUG:root:Listed 0 processes using CSRSS
DEBUG:root:Listed 0 processes using PspCidTable
DEBUG:root:Listed 0 processes using PsActiveProcessHead
DEBUG:root:Listed 0 processes using CSRSS
DEBUG:root:Listed 0 processes using PspCidTable
DEBUG:root:Listed 0 processes using Sessions
DEBUG:root:Listed 0 processes using Handles
DEBUG:root:Listed 0 processes using Sessions
DEBUG:root:Listed 0 processes using Handles

**Comment by scudette** [comment]
Can you please try the following:

1. Can you please re-sync the profile repository. There was a MS patch a few weeks ago which upgraded all versions of the kernels and the new profiles you reported (the GUIDs above were not synced with the repository). I just updated our repository.

2. Can you also please try Rekall release 1.3.1? There was a new feature added which goes directly to MS symbol server to download the missing profiles - even if they are missing from the local cache. This should hopefully fix future problems with MS patches introducing new kernels.

3. In Rekall 1.3.1 the --profile_path option was renamed to --repository_path because the python argparse library gets confused between --profile_path and --profile (since it tries to shorten the options). So you will need to specify it with --repository_path (you can also take advantage of that shortening and just specify --repo).

Thanks for reporting.

**Comment by l0gm0nk3y** [comment]
Got it working.  Thanks again!
