### ISSUE TITLE
Error when trying to download

### ISSUE THREAD

**Issue by ottoscav** [google/rekall#58]
Getting this error when trying to download linpmem

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
releases/19864741/7ca7ccca-d808-11e4-9b03-c281f258d515.0_alpha
</Key>
<RequestId>25D9503C87509A80</RequestId>
<HostId>
ycG5lqWAEmItYi7btbJmCcqBnigzMKr+EH8C1nu6P/eg6sBn9N5522NeeXuKL0jl
</HostId>
</Error>

**Comment by scudette** [comment]
Hey,
  Thanks for reporting! It seems that github suddenly lost our file? I
reuploaded the file, this time gzip compressed.

Thanks again
Michael.
