### ISSUE TITLE
Properly creating a portable Rekall on a USB stick

### ISSUE THREAD

**Issue by DigiAngel** [google/rekall#61]
Topic says it....I'd like to create a rekall instance on a USB stick....I currently have a halfway one by installing Rekall via the windows installer to my USB stick.  My goal is for incident response to just plug into a current running Windows machine and go.  Two things I need:

1.  Make it so that all the profiles are already on the USB stick
2.  Make it so the .recall_cache files and what not are all created on the USB stick

Any pointers for this?  Thank you.

**Comment by scudette** [comment]
I think you should be able to copy all the files in the installation directory `c:\program files\rekall` somewhere on the USB drive. These files are built with pyinstaller and we do not put any other files elsewhere.

Then you can write your own ~/.rekallrc file in the thumbdrive. Currently Rekall tries to find this file in the directory set by the %HOME% or %USERPROFILE% environment variables so you would need to set those with a bat script before launching the main executable. 

It seems that you have a specific use case in mind - so maybe also get the bat script to load winpmem and just open rekall with -f \\.\pmem?

You can then edit the .rekallrc file to point to your local copy of the profile repository (on the thumb drive). Just git clone it:

```
git clone https://github.com/google/rekall-profiles.git
```

and set the path to it in .rekallrc (this can be a relative path if you change to the drive first):

```
cache_dir: ./.rekall_cache
profile_path:
 - ./rekall-profiles/
```

You can then create the `.rekall_cache` directory on the drive. If you do not want a cache dir at all you can just set it to the empty string ("").

**Comment by scudette** [comment]
I forgot to mention that you can also specify the path to the repository and the cache dir using the command line flags so that might be easier than messing with the config file, but without the environment variable set to the thumb drive, Rekall will create a new default .rekallrc file in the user's home dir which may not be what you want.

```
  --repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]
                        Path to search for profiles. This can take any form
                        supported by the IO Manager (e.g. zip files,
                        directories, URLs etc)
  --cache_dir CACHE_DIR
                        Location of the profile cache directory.
```

**Comment by DigiAngel** [comment]
Thank you much...I will give this a try and report my results.

**Comment by DigiAngel** [comment]
Well this has been interesting.  So far here's what I have.  The usb drive is H:\ and rekall is at H:\Rekall64.  Other dirs:
H:\Rekall64\rekall-profiles
H:\Rekall64\rekall_cache
H:\Rekall64\.rekallrc

.rekallrc:
cache_dir: rekall_cache
profile_path: rekall-profiles

###########################################################
cd Rekall64
rekall -f \.\pmem --repository_path rekall-profiles --cache_dir rekall_cache

DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\inventory.gz
WARNING:root:Inventory for repository "C:\Users\username\rekall_cache" seems malformed. Are you behind a captive portal or proxy? If this is a custom repository, did you forget to create an inventory? You must use the tools/profiles/bu
ild_profile_repo.py tool with the --inventory flag. If this warning is for the cache directory, just ignore it.
DEBUG:root:Adding nt/eprocess_index to local cache.
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\nt\eprocess_index.gz
INFO:root:Loaded profile nt/eprocess_index from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Adding nt/index to local cache.
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\nt\index.gz
INFO:root:Loaded profile nt/index from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Adding OSX/index to local cache.
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\OSX\index.gz
INFO:root:Loaded profile OSX/index from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Adding pe to local cache.
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\pe.gz
INFO:root:Loaded profile pe from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Adding ntfs to local cache.
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\ntfs.gz
INFO:root:Loaded profile ntfs from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Skipped profile nt/GUID/36A91F6120C3416486536C2033CF33DF2 from rekall-profiles (Not in inventory)
DEBUG:root:Will build local profile nt/GUID/36A91F6120C3416486536C2033CF33DF2
ERROR:root:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlpa.pdb/36A91F6ERROR:root:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrpamp.pdb/36A91F6ERROR:root:Error: HTTP Error 404: Not Found
Microsoft (R) File Expansion Utility  Version 6.1.7600.16385
Copyright (c) Microsoft Corporation. All rights reserved.

Adding c:\users\username\appdata\local\temp\tmpqubltd\ntkrnlmp.pdb to Extraction Queue

Expanding Files ....

Expanding Files Complete ...
DEBUG:root:Adding mspdb to local cache.
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\mspdb.gz
INFO:root:Loaded profile mspdb from Local Cache Directory:C:\Users\username\rekall_cache
WARNING:root:Profile nt/GUID/36A91F6120C3416486536C2033CF33DF2 fetched and built. Please consider reporting this profile to the Rekall team so we may add it to the public profile repository.
DEBUG:root:Opened local file C:\Users\username\rekall_cache\v1.0\nt\GUID\36A91F6120C3416486536C2033CF33DF2.gz
INFO:root:Loaded profile nt/GUID/36A91F6120C3416486536C2033CF33DF2 from Local Cache Directory:C:\Users\username\rekall_cache
INFO:root:Detected ntkrnlmp.pdb with GUID 36A91F6120C3416486536C2033CF33DF2
DEBUG:root:Detection method rsds worked at offset 0x2fa874c
############################################

passing the variables appeared to do nothing at all.

Next up is setting environments instead:
############################################################
H:\Rekall64>set HOME=Rekall64
H:\Rekall64>set HOMEDRIVE=H:\
H:\Rekall64>winpmem_2.0.1.exe -l
Driver Unloaded.
CR3: 0x0000187000
 11 memory ranges:
Start 0x00001000 - Length 0x0009C000
Start 0x00100000 - Length 0x1FF00000
Start 0x20200000 - Length 0x1FE04000
Start 0x40005000 - Length 0x82A0E000
Start 0xC2A56000 - Length 0x04328000
Start 0xC7000000 - Length 0x00741000
Start 0xC7800000 - Length 0x007B4000
Start 0xC8000000 - Length 0x01720000
Start 0xC9800000 - Length 0x01724000
Start 0xCAFA6000 - Length 0x00001000
Start 0x100000000 - Length 0x12F600000
Memory access driver left loaded since you specified the -l flag.
H:\Rekall64>rekal.exe -v -f \\.\pmem
DEBUG:root:Will detect profile using these Detectors: nt_index,osx,pe,rsds,ntfs,linux
Traceback (most recent call last):
  File "<string>", line 86, in <module>
  File "<string>", line 59, in main
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.args", line 415, in parse_args
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 98, in Metadata
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugin", line 349, in GetActivePlugin
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugin", line 198, in is_active
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 784, in profile
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 519, in GetParameter
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 547, in _RunParameterHook
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.guess_profile", line 495, in calculate
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.guess_profile", line 422, in ScanProfiles
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.registry", line 56, in __call__
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.guess_profile", line 140, in __init__
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 728, in LoadProfile
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 438, in repository_managers
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.io_manager", line 558, in Factory
rekall.io_manager.IOManagerError: Unable to find any managers which can work on r
###########################################

Is there something I'm missing?  Thank you.

**Comment by scudette** [comment]
The first invocation seems to work - you can see Rekall is telling you:

```
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\inventory.gz
```
So it is using the profile repository from the right place. It then discovers that the local cache is not yet initialized (which is expected since you just made this directory):

```
WARNING:root:Inventory for repository "C:\Users\username\rekall_cache" seems malformed. Are you behind a captive portal or proxy? If this is a custom repository, did you forget to create an inventory? You must use the tools/profiles/bu
ild_profile_repo.py tool with the --inventory flag. If this warning is for the cache directory, just ignore it.
```

Finally it tries to locate the profile but decides that the required profile has the GUID 36A91F6120C3416486536C2033CF33DF2 but that is not in the repository. So Rekall goes off to microsoft and gets the profile from them instead (thats the next few lines). Rekall then parses the Microsoft PDB file and builds a local profile:

```
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\mspdb.gz
INFO:root:Loaded profile mspdb from Local Cache Directory:C:\Users\username\rekall_cache
WARNING:root:Profile nt/GUID/36A91F6120C3416486536C2033CF33DF2 fetched and built. Please consider reporting this profile to the Rekall team so we may add it to the public profile repository.
```

The profile is stored in the cache correctly. The next time you run Rekall it will just use the cached version by itself.

The only problem seems to be that the --cache_dir flag is not honored correctly, and it is using the home location instead. Rekall will look for the .rekallrc file in the following places in order:

1. Current directory .rekallrc
2. %HOME%/.rekallrc or %USERPROFILE%/.rekallrc

So I think its already picking the .rekallrc you have in your thumbdrive. Can you paste the content of that?  If you run it from H:\Rekall64 and have a .rekallrc in there you probably dont need to mess with the environment vars.

**Comment by DigiAngel** [comment]
Hi again.  Here's my h:\Rekall64\.rekallrc:
~~~
cache_dir: rekall_cache
profile_path: rekall-profiles
~~~
And the output of:  H:\Rekall64>rekal.exe -v -f \\.\pmem

~~~
DEBUG:root:Voting round with base: None
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:root:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:root:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:root:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:root:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:root:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
DEBUG:root:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:root:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
DEBUG:root:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
DEBUG:root:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'>
DEBUG:root:Succeeded instantiating Win32FileAddressSpace
DEBUG:root:Voting round with base: Win32FileAddressSpace
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:root:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:root:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:root:Failed instantiating VMemAddressSpace: Only VMEM files supported.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:root:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:root:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
DEBUG:root:Failed instantiating KCoreAddressSpace: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:root:Failed instantiating Elf64CoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
DEBUG:root:Failed instantiating LimeAddressSpace: Invalid Lime header signature
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
DEBUG:root:Failed instantiating AFF4AddressSpace: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'>
DEBUG:root:Failed instantiating Win32FileAddressSpace: Must be first Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
DEBUG:root:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
DEBUG:root:Failed instantiating FileAddressSpace: Must be first Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
DEBUG:root:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
DEBUG:root:Failed instantiating VTxPagedMemory: No more EPTs specified
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
DEBUG:root:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
DEBUG:root:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
INFO:root:Autodetected physical address space Win32FileAddressSpace
DEBUG:root:Will detect profile using these Detectors: nt_index,osx,pe,rsds,ntfs,linux
Traceback (most recent call last):
  File "<string>", line 86, in <module>
  File "<string>", line 59, in main
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.args", line 415, in parse_args
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 98, in Metadata
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugin", line 349, in GetActivePlugin
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugin", line 198, in is_active
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 784, in profile
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 519, in GetParameter
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 547, in _RunParameterHook
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.guess_profile", line 495, in calculate
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.guess_profile", line 422, in ScanProfiles
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.registry", line 56, in __call__
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.guess_profile", line 140, in __init__
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 728, in LoadProfile
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 438, in repository_managers
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.io_manager", line 558, in Factory
rekall.io_manager.IOManagerError: Unable to find any managers which can work on r

H:\Rekall64>
~~~

Thank you...I was not aware an inventory needed to be done after cloning the rekall-profiles.

**Comment by scudette** [comment]
I think your .rekallrc is wrong. Try this:

```
cache_dir: rekall_cache
profile_path: 
   - rekall-profiles
```

The profile_path is a list of paths, not a single string.

**Comment by scudette** [comment]
There is no need to touch the inventory after you clone the rekall-profiles (there should be one there already), the inventory must be created on the cache directory - it will be done automatically so you dont need to do anything, but we just notice that its not there the first time we run on a new (or cleared) cache directory.

**Comment by DigiAngel** [comment]
Ok...so I fixed that up to mirror exactly what you have above (and FYI tab characters are no workie ;)).  Here's the results:

~~~
H:\Rekall64>rekal.exe -v -f \\.\pmem
DEBUG:root:Voting round with base: None
<snip>
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\inventory.gz
DEBUG:root:Opened local file C:\Users\username\rekall_cache\v1.0\inventory.gz
DEBUG:root:Opened local file C:\Users\username\rekall_cache\v1.0\nt\eprocess_index.gz
INFO:root:Loaded profile nt/eprocess_index from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Opened local file C:\Users\username\rekall_cache\v1.0\nt\index.gz
INFO:root:Loaded profile nt/index from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Opened local file C:\Users\username\rekall_cache\v1.0\OSX\index.gz
INFO:root:Loaded profile OSX/index from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Opened local file C:\Users\username\rekall_cache\v1.0\pe.gz
INFO:root:Loaded profile pe from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Opened local file C:\Users\username\rekall_cache\v1.0\ntfs.gz
INFO:root:Loaded profile ntfs from Local Cache Directory:C:\Users\username\rekall_cache
DEBUG:root:Opened local file C:\Users\username\rekall_cache\v1.0\nt\GUID\36A91F6120C3416486536C2033CF33DF2.gz
INFO:root:Loaded profile nt/GUID/36A91F6120C3416486536C2033CF33DF2 from Local Cache Directory:C:\Users\username\rekall_cache
INFO:root:Detected ntkrnlmp.pdb with GUID 36A91F6120C3416486536C2033CF33DF2
DEBUG:root:Detection method rsds worked at offset 0x2fa874c
~~~

Still not using my specified cache.  Thank you.

**Comment by scudette** [comment]
Oh I see what is happening here. We allow the cache dir to be specified relative to the home directory:

https://github.com/google/rekall/blob/master/rekall/plugins/tools/caching_url_manager.py#L62

```
        if config.GetHomeDir():
            cache_dir = os.path.join(config.GetHomeDir(), cache_dir)
```

So if it is just rekall_cache it will add it to the home directory. I am not sure if this is a good idea, maybe we should simply default cache_dir to %HOME%/.rekall_cache or something.

So you have 2 options:

1. Specify the directory as an absolute path - this is possible to do with a bat script. See this:
http://stackoverflow.com/questions/1645843/resolve-absolute-path-from-relative-path-and-or-file-name

2. You can just set the current directory to be the HOME variable:

```
H:\Rekall64>set HOME=.
H:\Rekall64>rekal.exe -v -f \\.\pmem
```

**Comment by DigiAngel** [comment]
Hey hey there we go!

~~~
DEBUG:root:Will detect profile using these Detectors: nt_index,osx,pe,rsds,ntfs,linux
DEBUG:root:Opened local file H:\Rekall64\rekall-profiles\v1.0\inventory.gz
DEBUG:root:Opened local file H:\Rekall64\rekall_cache\v1.0\inventory.gz
DEBUG:root:Opened local file H:\Rekall64\rekall_cache\v1.0\nt\eprocess_index.gz
INFO:root:Loaded profile nt/eprocess_index from Local Cache Directory:H:\Rekall64\rekall_cache
DEBUG:root:Opened local file H:\Rekall64\rekall_cache\v1.0\nt\index.gz
INFO:root:Loaded profile nt/index from Local Cache Directory:H:\Rekall64\rekall_cache
DEBUG:root:Opened local file H:\Rekall64\rekall_cache\v1.0\OSX\index.gz
INFO:root:Loaded profile OSX/index from Local Cache Directory:H:\Rekall64\rekall_cache
DEBUG:root:Opened local file H:\Rekall64\rekall_cache\v1.0\pe.gz
INFO:root:Loaded profile pe from Local Cache Directory:H:\Rekall64\rekall_cache
DEBUG:root:Opened local file H:\Rekall64\rekall_cache\v1.0\ntfs.gz
INFO:root:Loaded profile ntfs from Local Cache Directory:H:\Rekall64\rekall_cache
DEBUG:root:Opened local file H:\Rekall64\rekall_cache\v1.0\nt\GUID\36A91F6120C3416486536C2033CF33DF2.gz
INFO:root:Loaded profile nt/GUID/36A91F6120C3416486536C2033CF33DF2 from Local Cache Directory:H:\Rekall64\rekall_cache
INFO:root:Detected ntkrnlmp.pdb with GUID 36A91F6120C3416486536C2033CF33DF2
DEBUG:root:Detection method rsds worked at offset 0x2fa874c
~~~

Thanks so much....would love to see a blog post or FAQ or something with creating a USB instance...it's one thing to be able to plug in and dump memory, it's another thing entirely to perform live forensics without touching the drive.  Thanks again.

James
