### ISSUE TITLE
'p session' is not same than 'print session'

### ISSUE THREAD

**Issue by aapo** [google/rekall#70]
Documentation (on http://www.rekall-forensic.com/docs/Manual/tutorial.html#_a_short_rekall_demo) says 

    (Note "p" is the shortcut command for "print")

But command 

    p session

prints only "Session"

And 

    print session 

prints "Rekall session Started on ... Config: ..." (as seen in documentation)

Happens with 1.2.1 and 1.3.1.

**Comment by scudette** [comment]
This should now be fixed.
