### ISSUE TITLE
pluginname + questionmark  -help shows wrong url

### ISSUE THREAD

**Issue by aapo** [google/rekall#71]
E.g. p? shows

    Link:
    http://www.rekall-forensic.com/epydoc/rekall.plugins.core.Printer-class.html

And consoles? shows

    http://www.rekall-forensic.com/epydoc/rekall.plugins.windows.malware.cmdhistory.Consoles-class.html

Correct URL is http://www.rekall-forensic.com/epydocs/rekall.plugins.core.Printer-class.html

Might be this:

    diff --git a/rekall/plugins/core.py b/rekall/plugins/core.py
    index 5440a24..0af8e85 100644
    --- a/rekall/plugins/core.py
    +++ b/rekall/plugins/core.py
    @@ -182,7 +182,7 @@ class Info(plugin.Command):
                 doc_string = cls_doc + init_doc
                 doc_string += (
                     "\n\nLink:\n"
    -                "http://www.rekall-forensic.com/epydoc/%s.%s-class.html"
    +                "http://www.rekall-forensic.com/epydocs/%s.%s-class.html"
                 "\n\n" % (item.__module__, item.__name__))
 
                 renderer.write(doc_string)

**Comment by scudette** [comment]
Thanks for reporting! I rebuilt the help profile and pushed it to the repository. This should be fixed now.
