### ISSUE TITLE
Rekall installer version for windows x86

### ISSUE THREAD

**Issue by mkorman90** [google/rekall#73]
Is there a plan to create one?

**Comment by scudette** [comment]
Yes! the next release we will have a win32 x86 installer. We are due to
release in approximately one month (certainly before DFRWS where we will be
giving a workshop).

**Comment by scudette** [comment]
The 1.4.1 release includes a 32 bit installer. Building is also described in the blog post:

http://rekall-forensic.blogspot.ch/2015/09/installing-rekall-on-windows.html
