### ISSUE TITLE
Different linux profiles with the same version string cannot be represented in the inventory

### ISSUE THREAD

**Issue by parkisan** [google/rekall#75]
This is a long-standing issue that should be resolved.

If you have two profiles the same. i.e:

3.X.X-a-b-c
3.X.X-a-b-c

And they are actually different profiles (because of different CONFIG options, compiler, etc). You can't have them both in the inventory.

The solution to this is moving to an index-based profile selection for Linux.

**Comment by scudette** [comment]
This is now fixed as linux profile selection is done automatically by index.
