### ISSUE TITLE
Both rekall-core and rekall_gui install a file named bin/rekal.py

### ISSUE THREAD

**Issue by ant1** [google/rekall#77]
Both rekall-core and rekall_gui install a file named bin/rekal.py,  so one overwrites the other

**Comment by scudette** [comment]
Yeah good point - they are the same file but should only be shipped in one package.

**Comment by ant1** [comment]
This was fixed in https://github.com/google/rekall/commit/cd2e373bf1fe9b385d53bf3ff5236fc521e971b9
