### ISSUE TITLE
When I try to setup.py install on Windows, it complains about gnureadline

### ISSUE THREAD

**Issue by ohjeongwook** [google/rekall#85]
Log following.

Processing dependencies for rekall==0+unknown
Searching for gnureadline==6.3.3
Reading https://pypi.python.org/simple/gnureadline/
Best match: gnureadline 6.3.3
Downloading https://pypi.python.org/packages/source/g/gnureadline/gnureadline-6.3.3.tar.gz#md5=c4af83c9a3fbeac8f2da9b5a7c60e51c
Processing gnureadline-6.3.3.tar.gz
Writing c:\users\jeongoh\appdata\local\temp\easy_install-_lxdus\gnureadline-6.3.3\setup.cfg
Running gnureadline-6.3.3\setup.py -q bdist_egg --dist-dir c:\users\jeongoh\appdata\local\temp\easy_install-_lxdus\gnureadline-6.3.3\egg-dist-tmp-awapxi
error: Setup script exited with Error: this module is not meant to work on Windows (try pyreadline instead)
...

**Comment by scudette** [comment]
Ok I just reproduced this. We added it as a dependency in OSX to work around another broken package. It is not needed for windows.

For now if installing with pip - just install the core package
```
pip install rekall-core
```

If installing from source just remove it from the dependencies in rekall/rekall-gui/setup.py and run setup.py install from there.

Note that when installing from source you need to run the setup.py in rekall-core first, then rekall-gui. The setup.py in the top level directory is a meta-package which just pulls the others from pip.

**Comment by scudette** [comment]
After doing some more testing i figured out that we actually need to install pyreadline on all operating systems instead of gnureadline. Without this ipython does not have command completion and rekall fails to start. 

```
pip install pyreadline
```
The rest of the installation should work ok.

**Comment by tweksteen** [comment]
This fix actually breaks the Linux build. pyreadline should only be installed on windows platform. The setup.py of IPython shows how to include conditional dependencies: 
https://github.com/ipython/ipython/blob/e51e50d36f2d05061ef7bdcea56531f5fca08f4c/setup.py#L206
There is also one for OSX, it might be what you were looking for.

**Comment by scudette** [comment]
Thanks for this. The method they use does not actually seem to work though on windows (i.e. it still does not install pyreadline automatically). This is fine as we can always just add the requirement on windows only. The IPython package seems to bring in the right dependencies on osx and linux so we dont need to explicitly specify anything for those.

**Comment by scudette** [comment]
I think this issue is fixed with the 1.4.1 release.
