### ISSUE TITLE
pmem 2.0.1 fails to extract PhysicalMemory stream

### ISSUE THREAD

**Issue by 4n6ist** [google/rekall#86]
- The version of rekall you're using: winpmem_2.0.1, linpmem_2.0.1
- The operating system used to run rekall: Windows 8.1, Ubuntu 14.04
- The version of python used to run rekall: N/A
- The suspected operating system of the memory image: Larger than 8G
- The complete command line you used to run rekall: 

>winpmem_2.0.1 --export /PhysicalMemory --output PhysicalMemory.raw RAMSAMPLE.aff4
>linpmem_2.0.1 --export /PhysicalMemory --output PhysicalMemory.raw RAMSAMPLE.aff4

When I run above commands for aff4 file containing large RAM dump, the command stopped processing and output the following messages:

"terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::resize

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

This message appears on winpmem. linpmem output no messages.

When RAM size is small such as 2G, command finished without problems.

**Comment by scudette** [comment]
Does this image work properly in rekall itself?
Am 26.08.2015 12:31 nachm. schrieb "4n6ist" <notifications@github.com>:

**Comment by 4n6ist** [comment]
I haven't tested thoroughly yet, but at least rekall 1.4.0.pre3 fails to detect appropriate profile. I got like following messages.
 
"C:\Program Files\Rekall>rekal -f E:\RAMSAMPLE.aff4 pslist
ERROR:rekall.1:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "<string>", line 32, in <module>
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.rekal", line 79, in main
...(snip)
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.guess_profile", line 568, in calculate
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details."

**Comment by scudette** [comment]
could you please repeat with the -v flag. Also can you please try running
the version_scan plugin with name_regex="krn":

rekal -v -f E:\RAMSAMPLE.aff4 version_scan --name_regex krnl

We need to ensure that we have the profile for this sample in the first
place.

Thanks
Michael.

**Comment by 4n6ist** [comment]
Here are output messages.

(pslist -v)
<pre>
DEBUG:rekall.1:Voting round with base: None
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'&gt;
DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'&gt;
DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'&gt;
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'&gt;
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'&gt;
DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.win32.WinPmemAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating WinPmemAddressSpace: Filename does not look like a device.
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'&gt;
INFO:rekall.1:Added aff4://5ca4a313-247c-4245-b1c9-6318774129bf/PhysicalMemory as physical memory
DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace
DEBUG:rekall.1:Voting round with base: AFF4AddressSpace
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'&gt;
DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'&gt;
DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'&gt;
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'&gt;
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'&gt;
DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.win32.WinPmemAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating WinPmemAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating Win32FileAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.standard.FileAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'&gt;
DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:rekall.1:Trying &lt;class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'&gt;
DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
INFO:rekall.1:Autodetected physical address space AFF4AddressSpace
DEBUG:rekall.1:Will detect profile using these Detectors: nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
DEBUG:rekall.1:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz
DEBUG:rekall.1:Opened local file C:\Users\4n6ist\.rekall_cache\v1.0\inventory.gz
DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
DEBUG:rekall.1:Opened local file C:\Users\4n6ist\.rekall_cache\v1.0\inventory.gz
DEBUG:rekall.1:Opened local file C:\Users\4n6ist\.rekall_cache\v1.0\nt\eprocess_index.gz
INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:C:\Users\4n6ist\.rekall_cache
DEBUG:rekall.1:Opened local file C:\Users\4n6ist\.rekall_cache\v1.0\nt\index.gz
INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:C:\Users\4n6ist\.rekall_cache
DEBUG:rekall.1:nt/GUID/30092BE745B24FE2A311A936E7B7486F2 matched offset 0x7283f+0xfffff800dae1f000=0xfffff800dae9183f ('\x90')
DEBUG:rekall.1:nt/GUID/30092BE745B24FE2A311A936E7B7486F2 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/91A7E90801BB4731A016DDD85BE077132 matched offset 0x1144d7+0xfffff800dae1f000=0xfffff800daf334d7 ('\xcc')
DEBUG:rekall.1:nt/GUID/91A7E90801BB4731A016DDD85BE077132 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/ACF28B9C60564DA6B31DDF2441DD117F2 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/ACF28B9C60564DA6B31DDF2441DD117F2 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/518768F0031C4F5C9C3211628CC6C8422 matched offset 0x7283f+0xfffff800dae1f000=0xfffff800dae9183f ('\x90')
DEBUG:rekall.1:nt/GUID/518768F0031C4F5C9C3211628CC6C8422 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/2C39F687423840E793308F28C4FDE0CD2 matched offset 0x4c0cdf+0xfffff800dae1f000=0xfffff800db2dfcdf ('\xcc')
DEBUG:rekall.1:nt/GUID/2C39F687423840E793308F28C4FDE0CD2 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/1B2D0DFE2FB942758D615C901BE046922 matched offset 0x17d09a+0xfffff800dae1f000=0xfffff800daf9c09a ('\xcc')
DEBUG:rekall.1:nt/GUID/1B2D0DFE2FB942758D615C901BE046922 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/54923DFDBC5646EBA3D3A3C89D6B4DEE2 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/54923DFDBC5646EBA3D3A3C89D6B4DEE2 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/80B61DF4CE8342FE98E7159D75D41A611 matched offset 0xfa691+0xfffff800dae1f000=0xfffff800daf19691 ('\xcc')
DEBUG:rekall.1:nt/GUID/80B61DF4CE8342FE98E7159D75D41A611 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/ADBB8940685E4448A748028B784C8F3A1 matched offset 0x171ef3+0xfffff800dae1f000=0xfffff800daf90ef3 ('\x90')
DEBUG:rekall.1:nt/GUID/ADBB8940685E4448A748028B784C8F3A1 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/0181181818444BFD80A540B7833CE7EF2 matched offset 0x3d1f4f+0xfffff800dae1f000=0xfffff800db1f0f4f ('\xcc')
DEBUG:rekall.1:nt/GUID/0181181818444BFD80A540B7833CE7EF2 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/DFB53A5B642D49649F3E6A8BB9ADEEAF2 matched offset 0x1cb5c+0xfffff800dae1f000=0xfffff800dae3bb5c ('\xcc')
DEBUG:rekall.1:nt/GUID/DFB53A5B642D49649F3E6A8BB9ADEEAF2 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/D1484B9D3AC94E829E75B4D30CB95F5F2 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/D1484B9D3AC94E829E75B4D30CB95F5F2 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/4A60DBC8103A4FDBA527C2DC6CA770CE2 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/4A60DBC8103A4FDBA527C2DC6CA770CE2 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/423320282DB842E7BA2B0BFC86A84D752 matched offset 0x15e6ea+0xfffff800dae1f000=0xfffff800daf7d6ea ('\xcc')
DEBUG:rekall.1:nt/GUID/423320282DB842E7BA2B0BFC86A84D752 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/C1CA6E0E486D490DBAA23F09BED5712B2 matched offset 0x86c2f+0xfffff800dae1f000=0xfffff800daea5c2f ('\xcc')
DEBUG:rekall.1:nt/GUID/C1CA6E0E486D490DBAA23F09BED5712B2 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/2AD167109D8B40A5A9B5C1DB0ABEE6732 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/2AD167109D8B40A5A9B5C1DB0ABEE6732 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/6CD494C38A164545B7F51EB6C0163E201 matched offset 0x171ef3+0xfffff800dae1f000=0xfffff800daf90ef3 ('\x90')
DEBUG:rekall.1:nt/GUID/6CD494C38A164545B7F51EB6C0163E201 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/D4C707F97CC04408AB5FFF4F755056782 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/D4C707F97CC04408AB5FFF4F755056782 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/FFFBFF4681DA4D1CA9AC045FFF5451C32 matched offset 0x99cea+0xfffff800dae1f000=0xfffff800daeb8cea ('\xcc')
DEBUG:rekall.1:nt/GUID/FFFBFF4681DA4D1CA9AC045FFF5451C32 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/112DAAE966E24FECA88022ED4F52F0D32 matched offset 0x1d510+0xfffff800dae1f000=0xfffff800dae3c510 ('\xcc')
DEBUG:rekall.1:nt/GUID/112DAAE966E24FECA88022ED4F52F0D32 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/BF017A60357040F38AE1898B0699DE4B2 matched offset 0x99c5f+0xfffff800dae1f000=0xfffff800daeb8c5f ('\xcc')
DEBUG:rekall.1:nt/GUID/BF017A60357040F38AE1898B0699DE4B2 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/CB4676D61D9246D8B33B9BBD557A9C761 matched offset 0xfa691+0xfffff800dae1f000=0xfffff800daf19691 ('\xcc')
DEBUG:rekall.1:nt/GUID/CB4676D61D9246D8B33B9BBD557A9C761 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/2AC92539E58E44BB96E93D50FA59EDFA2 matched offset 0x41709f+0xfffff800dae1f000=0xfffff800db23609f ('\xcc')
DEBUG:rekall.1:nt/GUID/2AC92539E58E44BB96E93D50FA59EDFA2 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/4FF9EE0B265B4F05B61C3076F544FFB72 matched offset 0x208520+0xfffff800dae1f000=0xfffff800db027520 ('\x90')
DEBUG:rekall.1:nt/GUID/4FF9EE0B265B4F05B61C3076F544FFB72 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/5FB647682585460196DBF36D2E3CC3A02 matched offset 0x4c358f+0xfffff800dae1f000=0xfffff800db2e258f ('\xcc')
DEBUG:rekall.1:nt/GUID/5FB647682585460196DBF36D2E3CC3A02 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/4898BBC1322A4674A96BBF7EFFD68B432 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/4898BBC1322A4674A96BBF7EFFD68B432 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/D33E4FD471EE40A88553DFC645BB374E2 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/D33E4FD471EE40A88553DFC645BB374E2 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/77C608F2ED2B411A9FBF7C9CC6F23D482 matched offset 0x1159c5+0xfffff800dae1f000=0xfffff800daf349c5 ('\xcc')
DEBUG:rekall.1:nt/GUID/77C608F2ED2B411A9FBF7C9CC6F23D482 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/89017B70BAA9436FB806242D31DC30602 matched offset 0x1038f7+0xfffff800dae1f000=0xfffff800daf228f7 ('\xcc')
DEBUG:rekall.1:nt/GUID/89017B70BAA9436FB806242D31DC30602 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x51ecd0+0xfffff800dae1f000=0xfffff800db33dcd0 ('KernelSpace')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x670b50+0xfffff800dae1f000=0xfffff800db48fb50 ('IRP_MN_QUERY_DEVICE_TEXT')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x38a408+0xfffff800dae1f000=0xfffff800db1a9408 ('V\x00e\x00n\x00d\x00o\x00r\x00I\x00d\x00')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x38a3a0+0xfffff800dae1f000=0xfffff800db1a93a0 ('~\x00M\x00H\x00z\x00')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x140843+0xfffff800dae1f000=0xfffff800daf5f843 ('\xcc')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x473d6b+0xfffff800dae1f000=0xfffff800db292d6b ('\xcc')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x10041b+0xfffff800dae1f000=0xfffff800daf1f41b ('\xcc')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x40b867+0xfffff800dae1f000=0xfffff800db22a867 ('\xcc')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x156e4f+0xfffff800dae1f000=0xfffff800daf75e4f ('\x90')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x8b0db+0xfffff800dae1f000=0xfffff800daeaa0db ('\xcc')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x5f4447+0xfffff800dae1f000=0xfffff800db413447 ('\xcc')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matched offset 0x5b5737+0xfffff800dae1f000=0xfffff800db3d4737 ('\xcc')
DEBUG:rekall.1:nt/GUID/E39EBDC70D014E1BBCC9DCE5B19DBDEE1 matches 12/13 comparison points
DEBUG:rekall.1:nt/GUID/F2B9435002C444E09DF218FE7F8BC2061 matched offset 0x1a7048+0xfffff800dae1f000=0xfffff800dafc6048 ('\x90')
DEBUG:rekall.1:nt/GUID/F2B9435002C444E09DF218FE7F8BC2061 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/7E9A3CAB626845DE8E10816E3080A3B72 matched offset 0x4c367f+0xfffff800dae1f000=0xfffff800db2e267f ('\xcc')
DEBUG:rekall.1:nt/GUID/7E9A3CAB626845DE8E10816E3080A3B72 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31 matched offset 0x150003+0xfffff800dae1f000=0xfffff800daf6f003 ('\xcc')
DEBUG:rekall.1:nt/GUID/BD8F451F3E754ED8A34B50560CEB08E31 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/3C3D1F7B52A9418B8F530AA3D48589532 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/3C3D1F7B52A9418B8F530AA3D48589532 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/6A7034D51A0341FABDB5C78C10C3F25C2 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/6A7034D51A0341FABDB5C78C10C3F25C2 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/E018720B8C414EF799EACB23114763921 matched offset 0x82de3+0xfffff800dae1f000=0xfffff800daea1de3 ('\xcc')
DEBUG:rekall.1:nt/GUID/E018720B8C414EF799EACB23114763921 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/E5D00A3A0D6E432B8901F5D25275FCB32 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/E5D00A3A0D6E432B8901F5D25275FCB32 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/59E6495A9F0847F88AB25E37262838602 matched offset 0x1d510+0xfffff800dae1f000=0xfffff800dae3c510 ('\xcc')
DEBUG:rekall.1:nt/GUID/59E6495A9F0847F88AB25E37262838602 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/CD7C34F898A04587977FD7000FCE60A32 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/CD7C34F898A04587977FD7000FCE60A32 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/A468411312274C68A666A3C6CB04B5FA2 matched offset 0x1b2bfb+0xfffff800dae1f000=0xfffff800dafd1bfb ('\xcc')
DEBUG:rekall.1:nt/GUID/A468411312274C68A666A3C6CB04B5FA2 matches 1/15 comparison points
DEBUG:rekall.1:nt/GUID/2E29B27FD004410C89711915A1D663F91 matched offset 0x1a7048+0xfffff800dae1f000=0xfffff800dafc6048 ('\x90')
DEBUG:rekall.1:nt/GUID/2E29B27FD004410C89711915A1D663F91 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/0E5AB8358A2B43A89176A472397A3F882 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/0E5AB8358A2B43A89176A472397A3F882 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/556138DE16DF44E3B477C2BA3C6AE4B92 matched offset 0x11557f+0xfffff800dae1f000=0xfffff800daf3457f ('\xcc')
DEBUG:rekall.1:nt/GUID/556138DE16DF44E3B477C2BA3C6AE4B92 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/556138DE16DF44E3B477C2BA3C6AE4B92 matches 2/13 comparison points
DEBUG:rekall.1:nt/GUID/19BA6296DB4D449081731F426E76F5832 matched offset 0x100a43+0xfffff800dae1f000=0xfffff800daf1fa43 ('\xcc')
DEBUG:rekall.1:nt/GUID/19BA6296DB4D449081731F426E76F5832 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/36A91F6120C3416486536C2033CF33DF2 matched offset 0x86c2f+0xfffff800dae1f000=0xfffff800daea5c2f ('\xcc')
DEBUG:rekall.1:nt/GUID/36A91F6120C3416486536C2033CF33DF2 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/F54FEABC56394F9FBF74719DE74DE8812 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/F54FEABC56394F9FBF74719DE74DE8812 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/9DC6BDB5764E4A2784C769C1097C421A1 matched offset 0x14e09f+0xfffff800dae1f000=0xfffff800daf6d09f ('\x90')
DEBUG:rekall.1:nt/GUID/9DC6BDB5764E4A2784C769C1097C421A1 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/922CA62236DC40E1B79990407089CDD12 matched offset 0x11557f+0xfffff800dae1f000=0xfffff800daf3457f ('\xcc')
DEBUG:rekall.1:nt/GUID/922CA62236DC40E1B79990407089CDD12 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/83E4F08A63F5419EB0077C1C21E44CED2 matched offset 0xe530+0xfffff800dae1f000=0xfffff800dae2d530 ('\xcc')
DEBUG:rekall.1:nt/GUID/83E4F08A63F5419EB0077C1C21E44CED2 matches 1/13 comparison points
DEBUG:rekall.1:nt/GUID/923E9854C34D413988DFA9989C97C3EA2 matched offset 0x9b42f+0xfffff800dae1f000=0xfffff800daeba42f ('\xcc')
DEBUG:rekall.1:nt/GUID/923E9854C34D413988DFA9989C97C3EA2 matches 1/14 comparison points
DEBUG:rekall.1:nt/GUID/7A6629B2016A41D3A5D3E7129430544D2 matched offset 0x11cd03+0xfffff800dae1f000=0xfffff800daf3bd03 ('\xcc')
DEBUG:rekall.1:nt/GUID/7A6629B2016A41D3A5D3E7129430544D2 matches 1/14 comparison points
DEBUG:rekall.1:Opened local file C:\Users\4n6ist\.rekall_cache\v1.0\OSX\index.gz
INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:C:\Users\4n6ist\.rekall_cache
DEBUG:rekall.1:Opened local file C:\Users\4n6ist\.rekall_cache\v1.0\pe.gz
INFO:rekall.1:Loaded profile pe from Local Cache Directory:C:\Users\4n6ist\.rekall_cache
DEBUG:rekall.1:Opened local file C:\Users\4n6ist\.rekall_cache\v1.0\ntfs.gz
INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:C:\Users\4n6ist\.rekall_cache
ERROR:rekall.1:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "<string>", line 32, in <module>
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.rekal", line 79, in main
..(snip)
  File "C:\cygwin\home\mic\projects\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.guess_profile", line 568, in calculate
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
</pre>

(version_scan --name_regex krnl)
<pre>
  Offset (P)             GUID/Version                         PDB
0x000165c0f410 E39EBDC70D014E1BBCC9DCE5B19DBDEE1 ntkrnlmp.pdb
0x00018c1a3444 992647BDB5AF440085589CEEBD21D40B1 dxgkrnl.pdb
0x000898894220 342413BC18B54F828C3C883F8C556F881 D:\build\user\2015_0731_144855_HotFix2015-08_AvCompile\source\build\avcli_smoke_utils\RU_DLS!Win32_vs110\bin\Release_Unicode_DLS_vs110\Win32\avgkrnlapix.pdb
</pre>

**Comment by scudette** [comment]
There is a new aff4export plugin in Rekall which should work better. 
```
rekall aff4export my_volume.aff4 -D /tmp/
```

There was a bug in the c++ code regarding exporting specifically (https://github.com/google/aff4/commit/d819e42989c8caa22b0efd624b4282b7d00e4ca7) so we would need to release a new build of winpmem soon.

**Comment by 4n6ist** [comment]
OK, I'll check it when a new build is released.

**Comment by scudette** [comment]
This should be fixed in the current release.
