### ISSUE TITLE
fetch_pdb broken

### ISSUE THREAD

**Issue by tklengyel** [google/rekall#88]
I've just installed the latest version from https://github.com/google/rekall/releases/download/v1.4.0/rekall-forensic_1.4.0_amd64.deb:

rekall fetch_pdb -F ntkrpamp.pdb --guid 684da42a30cc450f81c535b4d18944b12
usage: rekall [-] [-v] [-q] [--debug] [--output_style {concise,full}]
              [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
              [--pager PAGER] [--paging_limit PAGING_LIMIT]
              [--colors {auto,yes,no}] [-F {text,json,wide,test,data}]
              [--plugin [PLUGIN [PLUGIN ...]]] [-h]
              [--cache {file,memory,timed}]
              [--repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]]
              [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT]
              [--max_collector_cost MAX_COLLECTOR_COST] [--dtb DTB]
              [-o FILE_OFFSET] [--ept EPT [EPT ...]] [--timezone TIMEZONE]
              [--cache_dir CACHE_DIR]
              [--name_resolution_strategies [{Module,Symbol,Export} [{Module,Symbol,Export} ...]]]
              [--autodetect_build_local_tracked [AUTODETECT_BUILD_LOCAL_TRACKED [AUTODETECT_BUILD_LOCAL_TRACKED ...]]]
              [--pagefile [PAGEFILE [PAGEFILE ...]]]
              [--autodetect {nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux} [{nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux} ...]]
              [--autodetect_threshold AUTODETECT_THRESHOLD]
              [--autodetect_build_local {full,basic,none}]
              [--autodetect_scan_length AUTODETECT_SCAN_LENGTH]
rekall: error: argument -F/--format: invalid choice: 'ntkrpamp.pdb' (choose from 'text', 'json', 'wide', 'test', 'data')

This used to work at least up to version 1.1.0

**Comment by scudette** [comment]
Hmm it seems we have a clash between the short flag for two different options:
-F/--format
-F/--pdb_filename

Im not sure why argparser did not point this out? Anyway you can simply specify the long form of the flag:
```
rekal -v fetch_pdb --pdb_filename ntkrpamp.pdb --guid 684da42a30cc450f81c535b4d18944b12
```

Perhaps we should remove the short option of this flag for this plugin. Realistically this plugin is not used directly very much by a user - usually it is called automatically as part of the "build_local_plugin" plugin. So having a short flag is not really important.

**Comment by tklengyel** [comment]
It's being used for other use-cases outside Rekall ;) But sure, retiring the short flag would eliminate the confusion.

**Comment by woanware** [comment]
The "parse_pdb" command also appears to suffer with the same issue, but even supplying the "--pdb_filename" parameter does not resolve the command line parameter parsing

**Comment by scudette** [comment]
Note that the parse_pdb plugin takes a positional arg (i.e. without a flag):
```
$ rekal parse_pdb --help
usage: rekal [-v] [-q] [--debug] [--output_style {concise,full}]
             [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
             [--pager PAGER] [--paging_limit PAGING_LIMIT]
             [--colors {auto,yes,no}] [-F {text,json,wide,test,data}]
             [--plugin [PLUGIN [PLUGIN ...]]] [-h]
             [--cache {file,memory,timed}]
             [--repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]]
             [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT]
             [--max_collector_cost MAX_COLLECTOR_COST] [--home HOME]
             [--dtb DTB] [-o FILE_OFFSET] [--ept EPT [EPT ...]]
             [--timezone TIMEZONE] [--cache_dir CACHE_DIR]
             [--name_resolution_strategies [{Module,Symbol,Export} [{Module,Symbol,Export} ...]]]
             [--autodetect_build_local_tracked [AUTODETECT_BUILD_LOCAL_TRACKED [AUTODETECT_BUILD_LOCAL_TRACKED ...]]]
             [--pagefile [PAGEFILE [PAGEFILE ...]]]
             [--autodetect {nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux} [{nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux} ...]]
             [--autodetect_threshold AUTODETECT_THRESHOLD]
             [--autodetect_build_local {full,basic,none}]
             [--autodetect_scan_length AUTODETECT_SCAN_LENGTH] [--live]
             [--version] [-] [-D DUMP_DIR] [--profile_class PROFILE_CLASS]
             [--output_filename OUTPUT_FILENAME]
             [--windows_version WINDOWS_VERSION] [--concise]
             pdb_filename
rekal: error: argument pdb_filename is required
```

**Comment by scudette** [comment]
I dont think there is anything left to do on this issue? If so please reopen.

**Comment by tklengyel** [comment]
Something seems to be broken again with fetch_pdb using almost the latest master (commit 131d7555d5a02dc57f15be4bf852864421d78948). Going into the rekal shell and following http://www.rekall-forensic.com/docs/Manual/Plugins/General/FetchPDB.html works though. Did the semantics for invoking this plugin from the command line change?

rekall fetch_pdb --pdb_filename ntkrpamp.pdb --guid 684da42a30cc450f81c535b4d18944b12
usage: rekall [-v] [-q] [--debug] [--output_style {concise,full}]
              [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
              [--log_domain [{PageTranslation} [{PageTranslation} ...]]]
              [--pager PAGER] [--paging_limit PAGING_LIMIT]
              [--colors {auto,yes,no}] [-F FORMAT]
              [--plugin [PLUGIN [PLUGIN ...]]] [-h] [--cache CACHE]
              [--repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]]
              [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT]
              [--max_collector_cost MAX_COLLECTOR_COST] [--home HOME]
              [--logging_format LOGGING_FORMAT]
              [--performance {normal,fast,thorough}] [--live LIVE] [--dtb DTB]
              [-o FILE_OFFSET] [--ept EPT [EPT ...]] [--timezone TIMEZONE]
              [--cache_dir CACHE_DIR]
              [--highlighting_style {manni,igor,lovelace,xcode,vim,autumn,vs,rrt,native,perldoc,borland,tango,emacs,friendly,monokai,paraiso-dark,colorful,murphy,bw,pastie,algol_nu,paraiso-light,trac,default,algol,fruity}]
              [--name_resolution_strategies [{Module,Symbol,Export} [{Module,Symbol,Export} ...]]]
              [--autodetect_build_local_tracked [AUTODETECT_BUILD_LOCAL_TRACKED [AUTODETECT_BUILD_LOCAL_TRACKED ...]]]
              [--pagefile [PAGEFILE [PAGEFILE ...]]]
              [--autodetect {linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux} [{linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux} ...]]
              [--autodetect_threshold AUTODETECT_THRESHOLD]
              [--autodetect_build_local {full,basic,none}]
              [--autodetect_scan_length AUTODETECT_SCAN_LENGTH] [--version]
              [-] [--dump_dir DUMP_DIR]
              pdb_filename [guid]
rekall: error: unrecognized arguments: --pdb_filename --guid 684da42a30cc450f81c535b4d18944b12

**Comment by scudette** [comment]
Right - these parameters are positional as the help indicates:

```
pdb_filename [guid]
```
