### ISSUE TITLE
Reconstruct/Extract Memory Streams into Single Raw File?

### ISSUE THREAD

**Issue by fligi7** [google/rekall#95]
Is there any way to reconstruct/extract the acquired AFF4 memory streams back into a singular Raw file for additional types of analysis (strings, page analysis, contiguous view in hex editor)?

**Comment by scudette** [comment]
Yes: You can use the aff4export plugin:

```
$ mkdir /tmp/dump
$ rekal aff4export -D /tmp/dump/ ~/images/hank.aff4
```

This will dump all the streams into the same directory. You can also apply a regex.

You can also use the aff4ls to see all the streams in the volume:
```
$ rekal aff4ls ~/images/hank.aff4
     Size                         Original Name                                                                                             URN
--------------- -------------------------------------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------
749568          C:\Windows\System32\batmeter.dll                   aff4://6567a47c-dd5d-4060-9a39-399fe735d959/C%3A%5CWindows%5CSystem32%5Cbatmeter.dll
235008          C:\Windows\System32\winsta.dll                     aff4://6567a47c-dd5d-4060-9a39-399fe735d959/C%3A%5CWindows%5CSystem32%5Cwinsta.dll
52224           C:\Windows\System32\psbase.dll                     aff4://6567a47c-dd5d-4060-9a39-399fe735d959/C%3A%5CWindows%5CSystem32%5Cpsbase.dll
958464          C:\Windows\System32\actxprxy.dll                   aff4://6567a47c-dd5d-4060-9a39-399fe735d959/C%3A%5CWindows%5CSystem32%5Cactxprxy.dll
514560          C:\Windows\system32\drivers\csc.sys                aff4://6567a47c-dd5d-4060-9a39-399fe735d959/C%3A%5CWindows%5Csystem32%5Cdrivers%5Ccsc.sys
186880          C:\Windows\System32\logoncli.dll                   aff4://6567a47c-dd5d-4060-9a39-399fe735d959/C%3A%5CWindows%5CSystem32%5Clogoncli.dll
```

**Comment by fligi7** [comment]
Awesome. Thanks!

**Comment by fligi7** [comment]
As a follow-up, is there any way to extract only specific streams. And, if so, how? I apologize if this is all documented somewhere but a Google search and search of rekall-forensic.com documentation turned up nothing. Feel free to just point me toward some docs with all this info.

**Comment by scudette** [comment]
Sorry about the lack of documentation. These plugins are really new to this
latest release :-).

You can select the stream to extract using the --regex flag. You can
generally tell what flags each plugin takes by just adding -h or --help to
the end:

$ rekal aff4export ~/images/hank.aff4 -h

usage: rekal [-v] [-q] [--debug] [--output_style {concise,full}]

             [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]

...

             [--version] [-] [-D DUMP_DIR] [--regex REGEX]

             volume

...

Plugin aff4export options:

  -D DUMP_DIR, --dump_dir DUMP_DIR

                        Path suitable for dumping files. (Required)

  --regex REGEX         Regex of filenames to dump.

  volume                Volume to list.


Thanks

Michael.


Am 15.09.2015 07:02 schrieb "fligi7" <notifications@github.com>:

**Comment by fligi7** [comment]
Thanks for the info. That's great to know.
